# Generated by Django 5.2.7 on 2026-04-07 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("servicos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoRelatorioAtendimentosTecnico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "nome",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                (
                    "servico_adicional_faixa_etaria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuracoes_relatorio_faixa_etaria",
                        to="servicos.servico",
                        verbose_name="Servico adicional para faixa etaria",
                    ),
                ),
                (
                    "servicos_adicionais",
                    models.ManyToManyField(
                        blank=True,
                        related_name="configuracoes_relatorio_servicos_adicionais",
                        to="servicos.servico",
                        verbose_name="Servicos adicionais selecionados",
                    ),
                ),
                (
                    "servicos_adicionais_agrupados",
                    models.ManyToManyField(
                        blank=True,
                        related_name="configuracoes_relatorio_servicos_agrupados",
                        to="servicos.servico",
                        verbose_name="Servicos adicionais agrupados",
                    ),
                ),
                (
                    "servicos_adicionais_pcd",
                    models.ManyToManyField(
                        blank=True,
                        related_name="configuracoes_relatorio_servicos_pcd",
                        to="servicos.servico",
                        verbose_name="Servicos adicionais para PCD",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuracao do relatorio de atendimentos tecnico",
                "verbose_name_plural": "Configuracoes do relatorio de atendimentos tecnico",
            },
        ),
    ]
