# Generated by Django 5.2.7 on 2026-04-08 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_configuracao_cadunico_bolsa_familia'),
        ('servicos', '0004_alter_servico_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaorelatorioatendimentostecnico',
            options={'verbose_name': 'Configuração do relatorio de atendimentos tecnico', 'verbose_name_plural': 'Configurações do relatorio de atendimentos tecnico'},
        ),
        migrations.AlterModelOptions(
            name='configuracaorelatorioatividadescadunico',
            options={'verbose_name': 'Configurção do relatorio de atividades cadunico', 'verbose_name_plural': 'Configurações do relatorio de atividades cadunico'},
        ),
        migrations.AlterField(
            model_name='configuracaorelatorioatendimentostecnico',
            name='servico_adicional_faixa_etaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_relatorio_faixa_etaria', to='servicos.servico', verbose_name='Serviço adicional para faixa etaria'),
        ),
        migrations.AlterField(
            model_name='configuracaorelatorioatendimentostecnico',
            name='servicos_adicionais',
            field=models.ManyToManyField(blank=True, related_name='configuracoes_relatorio_servicos_adicionais', to='servicos.servico', verbose_name='Serviços adicionais selecionados'),
        ),
        migrations.AlterField(
            model_name='configuracaorelatorioatendimentostecnico',
            name='servicos_adicionais_agrupados',
            field=models.ManyToManyField(blank=True, related_name='configuracoes_relatorio_servicos_agrupados', to='servicos.servico', verbose_name='Serviços adicionais agrupados'),
        ),
        migrations.AlterField(
            model_name='configuracaorelatorioatendimentostecnico',
            name='servicos_adicionais_pcd',
            field=models.ManyToManyField(blank=True, related_name='configuracoes_relatorio_servicos_pcd', to='servicos.servico', verbose_name='Serviços adicionais para PCD'),
        ),
        migrations.AlterField(
            model_name='configuracaorelatorioatividadescadunico',
            name='bolsa_familia',
            field=models.ManyToManyField(blank=True, related_name='configuracoes_relatorio_atividades_bolsa_familia', to='servicos.servico', verbose_name='Serviços de bolsa familia'),
        ),
        migrations.AlterField(
            model_name='configuracaorelatorioatividadescadunico',
            name='cadastro_unico',
            field=models.ManyToManyField(blank=True, related_name='configuracoes_relatorio_atividades_cadastro_unico', to='servicos.servico', verbose_name='Serviços de cadastro unico'),
        ),
    ]
