# Generated by Django 5.2.7 on 2026-04-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_alter_configuracaorelatorioatendimentostecnico_options_and_more'),
        ('servicos', '0004_alter_servico_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaorelatorioatendimentostecnico',
            name='familias_grupos',
            field=models.ManyToManyField(blank=True, related_name='configuracoes_relatorio_familias_grupos', to='servicos.servico', verbose_name='Famílias participando de grupos'),
        ),
    ]
