# Generated by Django 5.2.7 on 2026-04-16 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0004_configuracaorelatorioatendimentostecnico_familias_grupos'),
        ('servicos', '0004_alter_servico_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaorelatorioatendimentostecnico',
            name='familias_grupos',
        ),
        migrations.AddField(
            model_name='configuracaorelatorioatendimentostecnico',
            name='familias_grupos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes_relatorio_familias_grupos', to='servicos.servico', verbose_name='Famílias participando de grupos'),
        ),
    ]
