# Generated by Django 5.2.7 on 2026-02-19 17:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('codigo', models.IntegerField(verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Código Área',
                'verbose_name_plural': 'Códigos Área',
            },
        ),
    ]
