# Generated by Django 5.2.7 on 2026-02-23 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0018_alter_agendamento_um_agendamento_por_servico_por_cidadao'),
        ('encaminhamentos', '0001_initial'),
        ('unidade_cras', '0006_unidadecras_latitude_unidadecras_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('resumo', models.TextField(blank=True, null=True, verbose_name='Resumo do acompanhamento')),
                ('profissional', models.CharField(blank=True, max_length=150, null=True, verbose_name='Profissional de referência')),
                ('orientacoes', models.TextField(blank=True, null=True, verbose_name='Orientações para unidade de destino')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos', to='agendamentos.agendamento', verbose_name='Agendamento')),
                ('codigo_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos', to='encaminhamentos.codigoarea', verbose_name='Código de área')),
                ('unidade_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos_destino', to='unidade_cras.unidadecras', verbose_name='Unidade de destino')),
                ('unidade_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos_origem', to='unidade_cras.unidadecras', verbose_name='Unidade de origem')),
            ],
            options={
                'verbose_name': 'Encaminhamento',
                'verbose_name_plural': 'Encaminhamentos',
            },
        ),
    ]
