# Generated by Django 5.2.7 on 2026-02-23 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0018_alter_agendamento_um_agendamento_por_servico_por_cidadao'),
        ('encaminhamentos', '0002_encaminhamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaminhamento',
            name='agendamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos', to='agendamentos.agendamento', unique=True, verbose_name='Agendamento'),
        ),
    ]
