# Generated by Django 5.2.7 on 2026-02-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0003_alter_encaminhamento_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaminhamento',
            name='unidade_destino',
            field=models.CharField(max_length=255, verbose_name='Unidade de destino'),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='unidade_origem',
            field=models.CharField(max_length=255, verbose_name='Unidade de origem'),
        ),
    ]
