# Generated by Django 5.2.7 on 2026-09-28 21:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('principio_ativo', models.CharField(max_length=200, verbose_name='Princípio Ativo')),
                ('forma_farmaceutica', models.CharField(choices=[('COMPRIMIDO', 'Comprimido'), ('CAPSULA', 'Cápsula'), ('DRAGEA', 'Drágea'), ('SOLUCAO_ORAL', 'Solução oral'), ('SUSPENSAO_ORAL', 'Suspensão oral'), ('XAROPE', 'Xarope'), ('GOTAS', 'Gotas'), ('SOLUCAO_INJETAVEL', 'Solução injetável'), ('POMADA', 'Pomada'), ('CREME', 'Creme'), ('GEL', 'Gel'), ('COLIRIO', 'Colírio'), ('SPRAY', 'Spray'), ('AEROSSOL', 'Aerossol'), ('SUPOSITORIO', 'Supositório'), ('ADESIVO', 'Adesivo'), ('PO', 'Pó'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Forma Farmacêutica')),
                ('concentracao', models.CharField(help_text='Ex.: 500, 10, 2,5', max_length=50, verbose_name='Dosagem/Concentração')),
                ('unidade_medida', models.CharField(choices=[('MG', 'mg'), ('G', 'g'), ('MCG', 'mcg'), ('ML', 'mL'), ('MG_ML', 'mg/mL'), ('MG_G', 'mg/g'), ('UI', 'UI'), ('UI_ML', 'UI/mL'), ('PERCENTUAL', '%')], max_length=20, verbose_name='Unidade de Medida')),
                ('via_administracao', models.CharField(choices=[('ORAL', 'Oral'), ('SUBLINGUAL', 'Sublingual'), ('INTRAVENOSA', 'Intravenosa'), ('INTRAMUSCULAR', 'Intramuscular'), ('SUBCUTANEA', 'Subcutânea'), ('TOPICA', 'Tópica'), ('OFTALMICA', 'Oftálmica'), ('OTOLOGICA', 'Otológica'), ('NASAL', 'Nasal'), ('INALATORIA', 'Inalatória'), ('RETAL', 'Retal'), ('VAGINAL', 'Vaginal'), ('TRANSDERMICA', 'Transdérmica')], max_length=30, verbose_name='Via de Administração')),
                ('controlado', models.BooleanField(default=False, verbose_name='Controlado')),
                ('classe_terapeutica', models.CharField(blank=True, max_length=150, null=True, verbose_name='Classe Terapêutica')),
                ('fabricante', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fabricante')),
                ('codigo_registro', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código/Registro ANVISA')),
                ('observacoes', models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nome', 'concentracao'],
                'constraints': [models.UniqueConstraint(fields=('nome', 'concentracao', 'unidade_medida', 'forma_farmaceutica'), name='medicamento_apresentacao_unica')],
            },
        ),
    ]
