# Generated by Django 5.2.7 on 2026-09-28 21:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_permissoes_grupos'),
        ('prontuario', '0077_receita'),
        ('unidade_posto', '0009_alter_servicounidadeposto_mesmo_expediente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade mínima (em unidades de dispensação) esperada em cada posto. 0 desativa o alerta.', verbose_name='Estoque Mínimo por Unidade'),
        ),
        migrations.CreateModel(
            name='LoteMedicamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero_lote', models.CharField(max_length=50, verbose_name='Número do Lote')),
                ('validade', models.DateField(verbose_name='Validade')),
                ('quantidade_inicial', models.PositiveIntegerField(verbose_name='Quantidade Inicial')),
                ('quantidade_atual', models.PositiveIntegerField(default=0, verbose_name='Quantidade Atual')),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fornecedor')),
                ('data_entrada', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de Entrada')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='medicamentos.medicamento', verbose_name='Medicamento')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_medicamento', to='unidade_posto.unidadeposto', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Lote de Medicamento',
                'verbose_name_plural': 'Lotes de Medicamento',
                'ordering': ['validade', 'data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída/Dispensação'), ('AJUSTE', 'Ajuste de inventário'), ('PERDA', 'Perda/Descarte')], max_length=20, verbose_name='Tipo')),
                ('quantidade', models.IntegerField(help_text='Efeito no saldo do lote: positivo para entradas, negativo para saídas e perdas.', verbose_name='Quantidade')),
                ('saldo_apos', models.PositiveIntegerField(verbose_name='Saldo do Lote Após a Movimentação')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('motivo', models.TextField(blank=True, max_length=600, null=True, verbose_name='Motivo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='medicamentos.lotemedicamento', verbose_name='Lote')),
                ('receita_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensacoes', to='prontuario.receitamedicamento', verbose_name='Item de Receita Dispensado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data'],
            },
        ),
        migrations.AddConstraint(
            model_name='lotemedicamento',
            constraint=models.UniqueConstraint(fields=('medicamento', 'unidade', 'numero_lote'), name='lote_unico_por_medicamento_unidade'),
        ),
    ]
