# Generated by Django 5.2.7 on 2026-10-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0004_permissoes_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='concentracao',
            field=models.CharField(help_text='Ex.: 500, 10, 2,5. Descrições complexas do catálogo também são aceitas.', max_length=300, verbose_name='Dosagem/Concentração'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='observacoes',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='unidade_medida',
            field=models.CharField(choices=[('MG', 'mg'), ('G', 'g'), ('MCG', 'mcg'), ('ML', 'mL'), ('MG_ML', 'mg/mL'), ('MG_G', 'mg/g'), ('UI', 'UI'), ('UI_ML', 'UI/mL'), ('PERCENTUAL', '%'), ('NAO_SE_APLICA', 'Não se aplica / não identificada')], max_length=20, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='via_administracao',
            field=models.CharField(choices=[('ORAL', 'Oral'), ('SUBLINGUAL', 'Sublingual'), ('INTRAVENOSA', 'Intravenosa'), ('INTRAMUSCULAR', 'Intramuscular'), ('SUBCUTANEA', 'Subcutânea'), ('TOPICA', 'Tópica'), ('OFTALMICA', 'Oftálmica'), ('OTOLOGICA', 'Otológica'), ('NASAL', 'Nasal'), ('INALATORIA', 'Inalatória'), ('RETAL', 'Retal'), ('VAGINAL', 'Vaginal'), ('TRANSDERMICA', 'Transdérmica'), ('NAO_INFORMADA', 'Não informada')], max_length=30, verbose_name='Via de Administração'),
        ),
    ]
