# Generated by Django 5.2.7 on 2026-10-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0005_alter_medicamento_concentracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='forma_farmaceutica',
            field=models.CharField(choices=[('COMPRIMIDO', 'Comprimido'), ('COMPRIMIDO_ORODISPERSIVEL', 'Comprimido orodispersível'), ('COMPRIMIDO_SOLUVEL', 'Comprimido solúvel'), ('COMPRIMIDO_LIB_RETARDADA', 'Comprimido de liberação retardada'), ('CAPSULA', 'Cápsula'), ('DRAGEA', 'Drágea'), ('SOLUCAO_ORAL', 'Solução oral'), ('SUSPENSAO_ORAL', 'Suspensão oral'), ('XAROPE', 'Xarope'), ('GOTAS', 'Gotas'), ('SOLUCAO_INJETAVEL', 'Solução injetável'), ('PO_SOLUCAO_INJETAVEL', 'Pó para solução injetável'), ('SUSPENSAO_INJETAVEL', 'Suspensão injetável'), ('PO_SUSP_INJETAVEL', 'Pó para suspensão injetável'), ('SOL_INJETAVEL_5ML', 'Solução injetável 5 mL'), ('SOL_INJETAVEL_10ML', 'Solução injetável 10 mL'), ('SOL_INJETAVEL_100ML', 'Solução injetável 100 mL'), ('SOL_INJETAVEL_500ML', 'Solução injetável 500 mL'), ('POMADA', 'Pomada'), ('CREME', 'Creme'), ('CREME_VAGINAL', 'Creme vaginal'), ('GEL', 'Gel'), ('COLIRIO', 'Colírio'), ('SPRAY', 'Spray'), ('AEROSSOL', 'Aerossol'), ('SUPOSITORIO', 'Supositório'), ('ADESIVO', 'Adesivo'), ('PO', 'Pó'), ('GOMA_MASCAR', 'Goma de mascar'), ('PASTILHA', 'Pastilha'), ('PRESERVATIVO_160X49', 'Preservativo 160 mm x 49 mm'), ('PRESERVATIVO_160X52', 'Preservativo 160 mm x 52 mm'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Forma Farmacêutica'),
        ),
    ]
