# Generated by Django 5.2.7 on 2025-12-05 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidade_cras', '0003_guiche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.CharField(max_length=200, unique=True, verbose_name='Prontuário')),
                ('unidade_inicial', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='unidade_cras.unidadecras', verbose_name='Unidade Inicial')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
