# Generated by Django 5.2.7 on 2025-12-09 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('cidadaos', '0005_cidadao_apelido_cidadao_data_emissao_rg_cidadao_nis_and_more'),
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficioSocial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormaIngresso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('opcao', models.CharField(max_length=150, verbose_name='Forma de Ingresso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrgaoOrigemEncaminhamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('orgao', models.CharField(max_length=50, verbose_name='Orgão')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('unidade', models.CharField(max_length=150, verbose_name='Unidade')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.orgaoorigemencaminhamento', verbose_name='Orgão')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaReferencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('complemento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('cidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('ponto_referencia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ponto de Referência')),
                ('localizacao', models.CharField(blank=True, choices=[('URBANO', 'Urbano'), ('RURAL', 'Rural')], max_length=50, null=True, verbose_name='Localização do Domicílio')),
                ('abrigo', models.BooleanField(blank=True, null=True, verbose_name='Endereço é de um Abrigo')),
                ('contato_encaminhamento', models.CharField(max_length=150, verbose_name='Contato')),
                ('razoes', models.TextField(verbose_name='Razões, demandas ou necessidades do primeiro encaminhamento')),
                ('especifidade_familia', models.CharField(choices=[('SITUACAO_RUA', 'Família/pessoa em situação de rua'), ('RIBEIRINHA', 'Família ribeirinha'), ('ALDEIA', 'Família indígina residente em aldeia/reserva'), ('QUILOMBOLA', 'Família quilombola'), ('CIGANA', 'Família indígina não residente em aldeia/reserva')], max_length=150, verbose_name='Especifidade social')),
                ('povo_etinia', models.CharField(max_length=250, verbose_name='Especifique o povo.atnia (residente)')),
                ('bairro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.bairro', verbose_name='Bairro')),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.beneficiosocial', verbose_name='Bebefícios Socials')),
                ('forma_ingresso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.formaingresso', verbose_name='Forma de ingresso')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.orgaoorigemencaminhamento', verbose_name='Orgão')),
                ('pessoa_referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidadaos.cidadao', unique=True, verbose_name='Pessoa de Referência')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', unique=True, verbose_name='Prontuário')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.unidade', verbose_name='Unidade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
