# Generated by Django 5.2.7 on 2025-12-09 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0002_beneficiosocial_formaingresso_and_more'),
        ('unidade_cras', '0003_guiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoareferencia',
            name='povo_etinia',
            field=models.CharField(max_length=250, verbose_name='Especifique o povo/etnia (residente)'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='unidade_inicial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidade_cras.unidadecras', verbose_name='Unidade Inicial'),
        ),
    ]
