# Generated by Django 5.2.7 on 2025-12-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0003_alter_pessoareferencia_povo_etinia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoareferencia',
            name='beneficio',
        ),
        migrations.AddField(
            model_name='pessoareferencia',
            name='beneficio',
            field=models.ManyToManyField(to='prontuario.beneficiosocial', verbose_name='Bebefícios Socials'),
        ),
    ]
