# Generated by Django 5.2.7 on 2025-12-09 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0004_remove_pessoareferencia_beneficio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoareferencia',
            name='beneficio',
            field=models.ManyToManyField(blank=True, null=True, to='prontuario.beneficiosocial', verbose_name='Bebefícios Socials'),
        ),
        migrations.AlterField(
            model_name='pessoareferencia',
            name='contato_encaminhamento',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='pessoareferencia',
            name='especifidade_familia',
            field=models.CharField(blank=True, choices=[('SITUACAO_RUA', 'Família/pessoa em situação de rua'), ('RIBEIRINHA', 'Família ribeirinha'), ('ALDEIA', 'Família indígina residente em aldeia/reserva'), ('QUILOMBOLA', 'Família quilombola'), ('CIGANA', 'Família indígina não residente em aldeia/reserva')], max_length=150, null=True, verbose_name='Especifidade social'),
        ),
        migrations.AlterField(
            model_name='pessoareferencia',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.orgaoorigemencaminhamento', verbose_name='Orgão'),
        ),
        migrations.AlterField(
            model_name='pessoareferencia',
            name='povo_etinia',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Especifique o povo/etnia (residente)'),
        ),
        migrations.AlterField(
            model_name='pessoareferencia',
            name='razoes',
            field=models.TextField(blank=True, null=True, verbose_name='Razões, demandas ou necessidades do primeiro encaminhamento'),
        ),
        migrations.AlterField(
            model_name='pessoareferencia',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.unidade', verbose_name='Unidade'),
        ),
    ]
