# Generated by Django 5.2.7 on 2025-12-10 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadaos', '0005_cidadao_apelido_cidadao_data_emissao_rg_cidadao_nis_and_more'),
        ('prontuario', '0005_alter_pessoareferencia_beneficio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=150, verbose_name='Parentesco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembroComposicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('responsavel', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composicoes', to='cidadaos.cidadao')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='prontuario.prontuario')),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.parentesco', verbose_name='Parentesco')),
            ],
        ),
        migrations.CreateModel(
            name='ExclusaoMembroComposicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_exclusao', models.DateField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exclusoes', to='prontuario.membrocomposicao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='membrocomposicao',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('prontuario', 'cidadao'), name='uniq_membro_ativo_por_prontuario'),
        ),
    ]
