# Generated by Django 5.2.7 on 2025-12-10 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0006_parentesco_membrocomposicao_exclusaomembrocomposicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrocomposicao',
            name='parentesco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.parentesco', verbose_name='Parentesco'),
        ),
    ]
