# Generated by Django 5.2.7 on 2025-12-11 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0007_alter_membrocomposicao_parentesco'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbastecimentoAgua',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_abastecimento', models.CharField(max_length=150, verbose_name='Abastecimento de água')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CondicaoHabitacional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_residencia', models.CharField(choices=[('PROPRIA', 'Própria'), ('ALUGADA', 'Alugada'), ('CEDIDA', 'Cedida'), ('OCUPADA', 'Ocupada')], max_length=150, verbose_name='Tipo de residência')),
                ('material', models.CharField(blank=True, choices=[('ALVENARIA', 'Alvenaria ou madeira aparelhada'), ('MADEIRA', 'Madeira aproveitada / taipa / materiais precários')], max_length=150, null=True, verbose_name='Material das paredes externas')),
                ('acesso_eletrico', models.CharField(blank=True, choices=[('MEDIDOR_PROPRIO', 'Sim, com medidor próprio'), ('MEDIDOR_COMPARTILHADO', 'Sim, com medidor compartilhado'), ('SEM_MEDIDOR', 'Sim, sem medidor'), ('NAO_POSSUI', 'Não possui energia elétrica')], max_length=150, null=True, verbose_name='Acesso à energia elétrica')),
                ('agua_canalizada', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=10, null=True, verbose_name='Possui água canalizada?')),
                ('esgotamento', models.CharField(blank=True, choices=[('REDE_COLETORA', 'Rede coletora/ esgoto/ pluvial'), ('SEPTICA', 'Fossa séptica'), ('RUDIMENTAR', 'Fossa rudimentar'), ('DIRETO', 'Direto para rio/ lago/ mar'), ('SEM_BANHEIRO', 'Domicílio sem banheiro')], max_length=150, null=True, verbose_name='Esgotamento sanitário')),
                ('coleta', models.CharField(blank=True, choices=[('COLETA_DIRETA', 'Sim, coleta direta'), ('COLETA_INDIRETA', 'Sim, coleta indireta'), ('NAO_POSSUI', 'Não possui coleta')], max_length=150, null=True, verbose_name='Coleta de lixo')),
                ('total_comodos', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número total de cômodos')),
                ('total_dormitorios', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número total de dormitórios')),
                ('media_dormitorios', models.IntegerField(blank=True, null=True, verbose_name='Média de pessoas por domitório')),
                ('locomocao', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=10, null=True, verbose_name='O domicílio possue acessibilidade para pessoas com dificuldade de locomoção')),
                ('area_risco', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=10, null=True, verbose_name='Área de risco (desabamento/alagamento)?')),
                ('dificil_acesso', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=10, null=True, verbose_name='Domicílio em área de difícil acesso?')),
                ('area_conflito', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=10, null=True, verbose_name='Domicílio em área com conflito/violência?')),
                ('outras_observacoes', models.TextField(blank=True, null=True, verbose_name='Outras observações referentes ao diagnóstico das condições habitacionais da família')),
                ('abastecimento_agua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.abastecimentoagua', verbose_name='Abastecimento de água')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condicoes_habitacionais', to='prontuario.prontuario')),
            ],
            options={
                'verbose_name': 'Condição Habitacional',
                'verbose_name_plural': 'CondiçõesHabitacionais',
            },
        ),
    ]
