# Generated by Django 5.2.7 on 2025-12-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0008_abastecimentoagua_condicaohabitacional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abastecimentoagua',
            options={'verbose_name': 'Abastecimento de água', 'verbose_name_plural': 'Abastecimentos de água'},
        ),
        migrations.AlterModelOptions(
            name='beneficiosocial',
            options={'verbose_name': 'Benefício Social', 'verbose_name_plural': 'Benefícios Sociais'},
        ),
        migrations.AlterModelOptions(
            name='condicaohabitacional',
            options={'verbose_name': 'Condição Habitacional', 'verbose_name_plural': 'Condições Habitacionais'},
        ),
        migrations.AlterModelOptions(
            name='exclusaomembrocomposicao',
            options={'verbose_name': 'Exclusão de Membro', 'verbose_name_plural': 'Exclusões de Membros'},
        ),
        migrations.AlterModelOptions(
            name='formaingresso',
            options={'verbose_name': 'Forma de Ingresso', 'verbose_name_plural': 'Formas de Ingresso'},
        ),
        migrations.AlterModelOptions(
            name='membrocomposicao',
            options={'verbose_name': 'Membro Composição', 'verbose_name_plural': 'Membros Composição'},
        ),
        migrations.AlterModelOptions(
            name='orgaoorigemencaminhamento',
            options={'verbose_name': 'Origem de Encaminhamento', 'verbose_name_plural': 'Origens de Encaminhamento'},
        ),
        migrations.AlterModelOptions(
            name='parentesco',
            options={'verbose_name': 'Parentesco', 'verbose_name_plural': 'Parentescos'},
        ),
        migrations.AlterModelOptions(
            name='pessoareferencia',
            options={'verbose_name': 'Pessoa de Referencia', 'verbose_name_plural': 'Pessoas de Referencias'},
        ),
        migrations.RemoveConstraint(
            model_name='membrocomposicao',
            name='uniq_membro_ativo_por_prontuario',
        ),
    ]
