# Generated by Django 5.2.7 on 2026-01-12 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadaos', '0006_alter_cidadao_telefone'),
        ('prontuario', '0009_alter_abastecimentoagua_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoEducacionalMembro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('escolaridade', models.CharField(choices=[('SEM_ESCOLARIDADE', 'Sem Escolaridade'), ('FUNDAMENTAL_INCOMPLETO', 'Ensino Fundamental Incompleto'), ('FUNDAMENTAL_COMPLETO', 'Ensino Fundamental Completo'), ('MEDIO_INCOMPLETO', 'Ensino Médio Incompleto'), ('MEDIO_COMPLETO', 'Ensino Médio Completo'), ('SUPERIOR_IMCOMPLETO', 'Ensino Superior Incompleto'), ('SUPERIOR_COMPLETO', 'Ensino Superior Completo')], max_length=150, null=True, verbose_name='Escolaridade')),
                ('alfabetizado', models.BooleanField(blank=True, default=True, null=True, verbose_name='Alfabetizado')),
                ('frequencia', models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular'), ('NAO_FREQUENTA', 'Não Frequenta'), ('EVADIDO', 'Evadido')], max_length=150, null=True, verbose_name='Frenquência Escolar')),
                ('situacao', models.CharField(blank=True, choices=[('CURSANDO', 'Cursando'), ('CONCLUIDO', 'Concluído'), ('EVADIDO', 'Evadido'), ('NUNCA_FREQUENTOU', 'Nunca Frequentou')], max_length=150, null=True, verbose_name='Situação Escolar')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações sobre a Condição Educacional do Membro')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidadaos.cidadao', verbose_name='Cidadão')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CondicaoEducacional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('efeito_descumprimento', models.CharField(blank=True, choices=[('ADVERTENCIA', '01 - Advertência'), ('BLOQUEIO', '02 - Bloqueio'), ('SUSPENSAO', '03 - Suspensão'), ('CANCELMENTO', '04 - Cancelamento')], max_length=150, null=True, verbose_name='Efeito Aplicado')),
                ('observacao_suspensao', models.TextField(blank=True, null=True, verbose_name='Observações sobre a suspensão solicitada')),
                ('outra_observacao', models.TextField(blank=True, null=True, verbose_name='Outras observações referentes ao diagnóstico')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário')),
                ('condicao_educacional_membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.condicaoeducacionalmembro', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Condição Educacional',
                'verbose_name_plural': 'Condições Educacionais',
            },
        ),
    ]
