# Generated by Django 5.2.7 on 2026-01-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0010_condicaoeducacionalmembro_condicaoeducacional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicaoeducacional',
            name='condicao_educacional_membro',
        ),
        migrations.AddField(
            model_name='condicaoeducacional',
            name='condicao_educacional_membro',
            field=models.ManyToManyField(blank=True, null=True, to='prontuario.condicaoeducacionalmembro', verbose_name='Membro'),
        ),
    ]
