# Generated by Django 5.2.7 on 2026-01-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0011_remove_condicaoeducacional_condicao_educacional_membro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condicaoeducacionalmembro',
            options={'verbose_name': 'Condição Educacional do Membro Famíliar', 'verbose_name_plural': 'Condições Educacionais dos Membros Famíliares'},
        ),
    ]
