# Generated by Django 5.2.7 on 2026-02-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0012_alter_condicaoeducacionalmembro_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='sequencial',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='numero',
            field=models.CharField(editable=False, max_length=200, unique=True, verbose_name='Prontuário'),
        ),
    ]
