# Generated by Django 5.2.7 on 2026-02-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0013_prontuario_sequencial_alter_prontuario_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoareferencia',
            name='forma_ingresso',
            field=models.CharField(choices=[('ESPONTANEA', 'Demanda Expontânea'), ('ATIVA', 'Busca Ativa'), ('PROTECAO_BASICA', 'Encaminhamento Proteção Social Básica'), ('PROTECAO_ESPECIal', 'Encaminhamento Proteção Social Especial'), ('SAUDE', 'Encaminhamento pela Saúde'), ('EDUCAÇÃO', 'Encaminhado pela Educação'), ('SETORIAIS', 'Outras políticas setoriais'), ('CONSELHO', 'Conselho Tutelas'), ('JUDICIARIO', 'Poder Judiciário'), ('DIREITOS', 'Sistema de Garantia de Direitos'), ('OUTROS', 'Outros Encaminhamentos')], verbose_name='Forma de ingresso'),
        ),
    ]
