# Generated by Django 5.2.7 on 2026-02-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0014_alter_pessoareferencia_forma_ingresso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoareferencia',
            name='orgao',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='orgao',
        ),
    ]
