# Generated by Django 5.2.7 on 2026-02-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0015_remove_pessoareferencia_orgao_remove_unidade_orgao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoareferencia',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.unidade', verbose_name='Órgão/Unidade'),
        ),
    ]
