# Generated by Django 5.2.7 on 2026-02-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0016_alter_pessoareferencia_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='unidade',
            field=models.CharField(max_length=150, verbose_name='Órgão/Unidade'),
        ),
    ]
