# Generated by Django 5.2.7 on 2026-02-13 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0017_alter_unidade_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicaoeducacionalmembro',
            name='cidadao',
        ),
        migrations.AddField(
            model_name='condicaoeducacionalmembro',
            name='membro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.membrocomposicao', verbose_name='Membro Composição'),
        ),
    ]
