# Generated by Django 5.2.7 on 2026-02-13 16:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0018_remove_condicaoeducacionalmembro_cidadao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicaoeducacional',
            name='efeito_descumprimento',
        ),
        migrations.RemoveField(
            model_name='condicaoeducacional',
            name='observacao_suspensao',
        ),
        migrations.RemoveField(
            model_name='condicaoeducacional',
            name='outra_observacao',
        ),
        migrations.AddField(
            model_name='condicaoeducacional',
            name='observacao_geral',
            field=models.TextField(blank=True, null=True, verbose_name='Observações gerais da Família'),
        ),
        migrations.CreateModel(
            name='DescumprimentoEducacional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_ocorrencia', models.DateField(auto_now_add=True, verbose_name='Data da ocorrência')),
                ('efeito_codigo', models.CharField(choices=[('ADVERTENCIA', '01 - Advertência'), ('BLOQUEIO', '02 - Bloqueio'), ('SUSPENSAO', '03 - Suspensão'), ('CANCELMENTO', '04 - Cancelamento')], max_length=150)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.membrocomposicao', verbose_name='Membro')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Descumprimento Educacional',
                'verbose_name_plural': 'Descumprimentos Educacional',
            },
        ),
        migrations.AddField(
            model_name='condicaoeducacional',
            name='descumprimento_educacional_membro',
            field=models.ManyToManyField(to='prontuario.descumprimentoeducacional', verbose_name='Descumprimento Educacional Membro'),
        ),
    ]
