# Generated by Django 5.2.7 on 2026-02-13 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0020_alter_pessoareferencia_forma_ingresso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicaoeducacional',
            name='prontuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', unique=True, verbose_name='Prontuário'),
        ),
    ]
