# Generated by Django 5.2.7 on 2026-02-18 16:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0021_alter_condicaoeducacional_prontuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabalhoRendimentoMembro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('condicao_ocupacao', models.CharField(blank=True, choices=[('NAO_TRABALHA', '0 - Não trabalha'), ('CONTA_PROPRIA', '1 - Conta própria(bico, autônomo)'), ('TRABALHADOR_RURAL', '2 - Trabalhador temporário em área rura'), ('SEM_CARTEIRA', '3 - Empregado sem carteira de trabalho assinada'), ('COM_CARTEIRA', '4 -  Empregado com carteira de trabalho assinada'), ('DOMESTICO_SEM', '5 - Trabalhador doméstico sem carteira de trabalho assinada'), ('DOMESTICO_COM', '6 - Trabalhador doméstico com carteira de trabalho assinada'), ('NAO_REMUNERADO', '7 - Trabalhador não-remunerado'), ('MILITAR_PUBLICO', '8 - Militar ou servidor público'), ('EMPREGADOR', '9 - Empregador'), ('ESTAGIARIO', '10 - Estagiário'), ('APRENDIZ', '11 - Aprendiz (em condição legal)')], null=True, verbose_name='Condição de Ocupação')),
                ('vinculo_empregatico', models.CharField(blank=True, choices=[('CLT', 'CLT'), ('AUTONOMO', 'Autônomo'), ('INFORMAL', 'Informal'), ('DESEMPREGADO', 'Desempregado')], null=True, verbose_name='Vínculo Empregatício')),
                ('renda_individual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Renda Individual')),
                ('carteira_assinada', models.BooleanField(blank=True, null=True, verbose_name='Carteira Assinada?')),
                ('aposentado_pensionista', models.BooleanField(verbose_name='Aposentado/Pensionista')),
                ('membro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.membrocomposicao', verbose_name='Membro Composição')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Condição Educacional do Membro Famíliar',
                'verbose_name_plural': 'Condições Educacionais dos Membros Famíliares',
            },
        ),
    ]
