# Generated by Django 5.2.7 on 2026-02-18 16:25

import prontuario.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0022_trabalhorendimentomembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhorendimentomembro',
            name='qualificacao_profissional',
            field=models.JSONField(blank=True, default=list, validators=[prontuario.validators.validate_qualificacoes]),
        ),
        migrations.AlterField(
            model_name='trabalhorendimentomembro',
            name='aposentado_pensionista',
            field=models.BooleanField(blank=True, null=True, verbose_name='Aposentado/Pensionista'),
        ),
    ]
