# Generated by Django 5.2.7 on 2026-02-18 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0023_trabalhorendimentomembro_qualificacao_profissional_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabalhorendimentomembro',
            options={'verbose_name': 'Trabalho e Rendimento do Membro', 'verbose_name_plural': 'Trabalhos e Rendimentos dos Membros'},
        ),
        migrations.AlterField(
            model_name='trabalhorendimentomembro',
            name='renda_individual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda Individual'),
        ),
        migrations.CreateModel(
            name='TransferenciaRenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da transferência')),
                ('beneficio', models.ManyToManyField(blank=True, null=True, to='prontuario.beneficiosocial', verbose_name='Benefícios Socials')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
