# Generated by Django 5.2.7 on 2026-02-18 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0024_alter_trabalhorendimentomembro_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferenciarenda',
            name='beneficio',
        ),
        migrations.AddField(
            model_name='transferenciarenda',
            name='beneficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.beneficiosocial', verbose_name='Benefícios Socials'),
        ),
    ]
