# Generated by Django 5.2.7 on 2026-02-18 17:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0025_remove_transferenciarenda_beneficio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabalhoRendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('renda_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda Total (Sem Benefícios)')),
                ('renda_per_capita', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda Per Capta')),
                ('parecer', models.TextField(blank=True, null=True, verbose_name='Diagnóstico Situacional')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário')),
                ('trabalho_rendimento_membro', models.ManyToManyField(blank=True, null=True, to='prontuario.trabalhorendimentomembro', verbose_name='Membro')),
                ('transferencia_renda_familia', models.ManyToManyField(blank=True, null=True, to='prontuario.transferenciarenda', verbose_name='Transferências de Renda (Família)')),
            ],
            options={
                'verbose_name': 'Trabalho e Rendimento',
                'verbose_name_plural': 'Trabalhos e Rendimentos',
            },
        ),
    ]
