# Generated by Django 5.2.7 on 2026-02-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0026_trabalhorendimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalhorendimentomembro',
            name='membro',
        ),
        migrations.AlterField(
            model_name='trabalhorendimento',
            name='prontuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', unique=True, verbose_name='Prontuário'),
        ),
    ]
