# Generated by Django 5.2.7 on 2026-02-18 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0027_remove_trabalhorendimentomembro_membro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhorendimentomembro',
            name='membro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.membrocomposicao', unique=True, verbose_name='Membro Composição'),
        ),
    ]
