# Generated by Django 5.2.7 on 2026-02-19 12:43

import django.db.models.deletion
import prontuario.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0028_trabalhorendimentomembro_membro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaudeCuidadosMembro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deficiencia', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Possui Deficiência?')),
                ('acompanhamento', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Acompanhamento Médico?')),
                ('doencas_graves', models.JSONField(blank=True, default=list, validators=[prontuario.validators.validate_doencas_graves])),
                ('cuidados_terceiros', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Necessita de cuidados de terceiros?')),
                ('remedio', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Remédio Controlado?')),
                ('alcool', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Uso de Álcool?')),
                ('drogas', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Uso de Drogas?')),
                ('tratamentos', models.TextField(blank=True, null=True, verbose_name='Tratamentos atuais')),
                ('medicamentos', models.TextField(blank=True, null=True, verbose_name='Medicamentos em uso')),
                ('gestante', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Gestante?')),
                ('meses_gestante', models.PositiveIntegerField(blank=True, null=True, verbose_name='Meses de gestação')),
                ('membro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.membrocomposicao', unique=True, verbose_name='Membro Composição')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Condição de Saúde do Membro',
                'verbose_name_plural': 'Condições de Saúde dos Membros',
            },
        ),
    ]
