# Generated by Django 5.2.7 on 2026-02-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0029_saudecuidadosmembro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoareferencia',
            name='especifidade_familia',
            field=models.CharField(blank=True, choices=[('SITUACAO_RUA', 'Família/pessoa em situação de rua'), ('RIBEIRINHA', 'Família ribeirinha'), ('ALDEIA', 'Família indígina residente em aldeia/reserva'), ('QUILOMBOLA', 'Família quilombola'), ('CIGANA', 'Família cigana'), ('INDIGINA_NAO_RESIDENTE', 'Família indígena não residente em aldeia/reserva')], max_length=150, null=True, verbose_name='Especifidade social'),
        ),
    ]
