# Generated by Django 5.2.7 on 2026-02-19 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0030_alter_pessoareferencia_especifidade_familia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescumprimentoCondicionalidadesBolsa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('efeito_codigo', models.CharField(choices=[('ADVERTENCIA', '1 - Advertência'), ('BLOQUEIO', '2 - Bloqueio'), ('SUSPENSAO', '3 - Suspensão'), ('CANCELAMENTO', '4 - Cancelamento')], verbose_name='Efeito/Código')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.membrocomposicao', verbose_name='Membro Composição')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Descumprimento de Condicionalidades',
                'verbose_name_plural': 'Descumprimentos de Condicionalidades',
            },
        ),
    ]
