# Generated by Django 5.2.7 on 2026-02-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0031_descumprimentocondicionalidadesbolsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descumprimentocondicionalidadesbolsa',
            name='efeito_codigo',
            field=models.CharField(choices=[('ADVERTENCIA', '01 - Advertência'), ('BLOQUEIO', '02 - Bloqueio'), ('SUSPENSAO', '03 - Suspensão'), ('CANCELMENTO', '04 - Cancelamento')], verbose_name='Efeito/Código'),
        ),
    ]
