# Generated by Django 5.2.7 on 2026-02-19 13:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0033_alter_descumprimentocondicionalidadesbolsa_efeito_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicoesDeSaude',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('inseguranca_alimentar', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Declara insegurança alimentar')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Outras observações Técnicas')),
                ('condicoes_saude_membro', models.ManyToManyField(blank=True, null=True, to='prontuario.saudecuidadosmembro', verbose_name='Membro')),
                ('descumprimento_condicionalidade', models.ManyToManyField(blank=True, null=True, to='prontuario.descumprimentocondicionalidadesbolsa', verbose_name='Descumprimento Saúde Membro')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Condição de Saúde',
                'verbose_name_plural': 'Condições de Saúde',
            },
        ),
    ]
