# Generated by Django 5.2.7 on 2026-02-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0034_condicoesdesaude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrocomposicao',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('REFERENCIA', 'Pessoa de Referência'), ('CONJUGE', 'Cônjuge/Companheiro(a)'), ('FILHO', 'Filho(a)'), ('PAI', 'Pai'), ('MAE', 'Mãe'), ('NETO', 'Neto(a)'), ('IRMAO_IRMA', 'Irmão/Irmã'), ('OUTRO', 'Outro')], null=True, verbose_name='Parentesco'),
        ),
    ]
