# Generated by Django 5.2.7 on 2026-02-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0035_alter_membrocomposicao_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicaohabitacional',
            name='abastecimento_agua',
            field=models.CharField(blank=True, choices=[('REDE', 'Rede geral de distribuição'), ('POCO', 'Poço, ou Nascente'), ('CISTERNA', 'Cisterna de captação'), ('CARRO', 'Carro Pipa'), ('OUTRA', 'Outra forma')], null=True, verbose_name='Abastecimento'),
        ),
    ]
