# Generated by Django 5.2.7 on 2026-02-19 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadaos', '0009_alter_cidadao_orgao_emissor_alter_cidadao_uf_rg'),
        ('prontuario', '0036_alter_condicaohabitacional_abastecimento_agua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrocomposicao',
            name='cidadao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composicoes', to='cidadaos.cidadao', unique=True),
        ),
    ]
