# Generated by Django 5.2.7 on 2026-02-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0037_alter_membrocomposicao_cidadao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicaoeducacional',
            name='descumprimento_educacional_membro',
            field=models.ManyToManyField(blank=True, null=True, to='prontuario.descumprimentoeducacional', verbose_name='Descumprimento Educacional Membro'),
        ),
    ]
