# Generated by Django 5.2.7 on 2026-02-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0038_alter_condicaoeducacional_descumprimento_educacional_membro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saudecuidadosmembro',
            name='doencas_graves',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Doenças Graves'),
        ),
    ]
