# Generated by Django 5.2.7 on 2026-02-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0039_alter_saudecuidadosmembro_doencas_graves'),
    ]

    operations = [
        migrations.AddField(
            model_name='saudecuidadosmembro',
            name='realiza_cuidados',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quem realiza os cuidados?'),
        ),
        migrations.AddField(
            model_name='saudecuidadosmembro',
            name='substancia',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Qual Substância?'),
        ),
    ]
