# Generated by Django 5.2.7 on 2026-02-20 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0040_saudecuidadosmembro_realiza_cuidados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiosEventuais',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('beneficio', models.CharField(choices=[('NATALIDADE', 'Auxílio Natalidade'), ('FUNERAL', 'Auxílio Funeral'), ('EMERGENCIA', 'Item/Kit Emergência'), ('BASICA', 'Cesta Básica'), ('ALUGUEL', 'Aluguel Social')], max_length=150, verbose_name='Tipo de Benefício')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações e Justificativa Técnica')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Benefício Eventual',
                'verbose_name_plural': 'Benefícios Eventuais',
            },
        ),
    ]
