# Generated by Django 5.2.7 on 2026-02-20 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0041_beneficioseventuais'),
        ('unidade_cras', '0006_unidadecras_latitude_unidadecras_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='descumprimentocondicionalidadesbolsa',
            name='data_ocorrencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Ocorrência'),
        ),
        migrations.CreateModel(
            name='ConvivenviaFortalecimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('servico', models.CharField(max_length=150, verbose_name='Nome do Serviço')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.membrocomposicao', verbose_name='Membro da Família')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário')),
                ('unidade_inicial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidade_cras.unidadecras', verbose_name='Unidade de realização')),
            ],
            options={
                'verbose_name': 'Convivenvia e Fortalecimento de Vínculo',
                'verbose_name_plural': 'Convivenvia e Fortalecimentos de Vínculos',
            },
        ),
    ]
