# Generated by Django 5.2.7 on 2026-02-20 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0042_descumprimentocondicionalidadesbolsa_data_ocorrencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiosServicos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('beneficios_eventuais', models.ManyToManyField(to='prontuario.beneficioseventuais', verbose_name='Benefícios Eventuais')),
                ('convivencia_e_fortalecimento', models.ManyToManyField(to='prontuario.convivenviafortalecimento', verbose_name='Convivencia e Fortalecimento')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Beneficio e Serviço',
                'verbose_name_plural': 'Beneficios e Serviços',
            },
        ),
    ]
