# Generated by Django 5.2.7 on 2026-02-23 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0043_beneficiosservicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiosservicos',
            name='beneficios_eventuais',
            field=models.ManyToManyField(blank=True, null=True, to='prontuario.beneficioseventuais', verbose_name='Benefícios Eventuais'),
        ),
        migrations.AlterField(
            model_name='beneficiosservicos',
            name='convivencia_e_fortalecimento',
            field=models.ManyToManyField(blank=True, null=True, to='prontuario.convivenviafortalecimento', verbose_name='Convivencia e Fortalecimento'),
        ),
        migrations.AlterField(
            model_name='beneficiosservicos',
            name='prontuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', unique=True, verbose_name='Prontuário'),
        ),
    ]
