# Generated by Django 5.2.7 on 2026-02-23 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0044_alter_beneficiosservicos_beneficios_eventuais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvivenciaFamiliar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tempo_estado', models.IntegerField(blank=True, null=True, verbose_name='Há quantos anos a família mora neste estado')),
                ('estado', models.BooleanField(blank=True, null=True, verbose_name='A família sempre morou')),
                ('tempo_municipio', models.IntegerField(blank=True, null=True, verbose_name='Há quantos anos a família mora no município')),
                ('municipio', models.BooleanField(blank=True, null=True, verbose_name='A família sempre morou')),
                ('tempo_bairro', models.IntegerField(blank=True, null=True, verbose_name='Há quantos anos a família mora no bairro atual')),
                ('bairro', models.BooleanField(blank=True, null=True, verbose_name='A família sempre morou')),
                ('vitima_ameaca', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Há algum ou alguns dos membros vítimas de ameaça')),
                ('parente_proximo', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='A família possui parentes que residem próximos')),
                ('vizinhos_apoio', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='A família possui vizinhos que constituam rede de apoio')),
                ('grupo_religioso', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='A família, ou algum de seus membros, participa de grupos religiosos')),
                ('movimento_social', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='A família, ou algum de seus membros, participa de movimentos sociais,')),
                ('atividade_lazer_crianca', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Criança não tem acesso a atividades de lazer')),
                ('atividade_lazer_idoso', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Idoso não tem acesso a atividades de lazer')),
                ('companhia_adulto', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Dependentes sem companhia de adulto')),
                ('conflitos_conjugais', models.CharField(blank=True, choices=[('COM_VIOLENCIA', 'Conflituoso, com violência'), ('SEM_VIOLENCIA', 'Conflituoso, sem violência'), ('SEM_CONFLICO', 'Sem conflitos relevantes')], null=True, verbose_name='Avaliação do técnico sobre as relações conjugais')),
                ('conflitos_responsaveis', models.CharField(blank=True, choices=[('COM_VIOLENCIA', 'Conflituoso, com violência'), ('SEM_VIOLENCIA', 'Conflituoso, sem violência'), ('SEM_CONFLICO', 'Sem conflitos relevantes')], null=True, verbose_name='Avaliação do técnico sobre as relações entre pais')),
                ('conflitos_irmaos', models.CharField(blank=True, choices=[('COM_VIOLENCIA', 'Conflituoso, com violência'), ('SEM_VIOLENCIA', 'Conflituoso, sem violência'), ('SEM_CONFLICO', 'Sem conflitos relevantes')], null=True, verbose_name='Avaliação do técnico sobre as relações entre os irmãos')),
                ('conflitos_outros', models.CharField(blank=True, choices=[('COM_VIOLENCIA', 'Conflituoso, com violência'), ('SEM_VIOLENCIA', 'Conflituoso, sem violência'), ('SEM_CONFLICO', 'Sem conflitos relevantes')], null=True, verbose_name='Indique se há relações conflituosas envolvendo outros indivíduos')),
                ('outras_observacoes', models.TextField(blank=True, null=True, verbose_name='Outras observações referentes ao diagnóstico das condições de convivência familiar e comunitária')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', unique=True, verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Convivência familiar e comunitária',
                'verbose_name_plural': 'Convivências familiares e comunitárias',
            },
        ),
    ]
