# Generated by Django 5.2.7 on 2026-02-23 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0045_convivenciafamiliar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcompanhamentoCreas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_final', models.DateField(verbose_name='Data Final')),
                ('identificao_creas', models.CharField(max_length=250, verbose_name='Identificação do Creas')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Acompanhamento Creas',
                'verbose_name_plural': 'Acompanhamentos Creas',
            },
        ),
        migrations.CreateModel(
            name='SituacaoViolencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('trabalho_infantil', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Situação de trabalho infantil')),
                ('negligencia', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Sofreu negligencia')),
                ('situacao_trabalho_rua', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Situação de Trabalho na Rua')),
                ('exploracao_sexual', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Vítima de exploração sexual?')),
                ('violencia_sexual', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Vítima de abuso ou violência sexual?')),
                ('violencia_fisica', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Vítima de violência física?')),
                ('violencia_psicologica', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Vítima de violência psicológica?')),
                ('trafico_pessoa', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Vítima de tráfico de pessoas?')),
                ('idoso_negligencia', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Idoso da família sofreu negligência?')),
                ('deficiente_negligencia', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Pessoa com deficiência sofreu negligência?')),
                ('violencia_patrimonial', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Vítima de violência patrimonial (Idoso ou PCD)?')),
                ('violencia_vivenciada', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Outra forma de violência vivenciada?')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações do Diagnóstico de Violência')),
                ('acompanhamento_creas', models.ManyToManyField(to='prontuario.acompanhamentocreas', verbose_name='AcompanhamentoCreas')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', unique=True, verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Situação de violência',
                'verbose_name_plural': 'Situações de violência',
            },
        ),
    ]
