# Generated by Django 5.2.7 on 2026-02-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0046_acompanhamentocreas_situacaoviolencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficioseventuais',
            name='cpf_falecido',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CPF da pessoa falecida'),
        ),
        migrations.AddField(
            model_name='beneficioseventuais',
            name='registro_nascimento',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Registro de nascimento'),
        ),
    ]
