# Generated by Django 5.2.7 on 2026-02-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0047_beneficioseventuais_cpf_falecido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacaoviolencia',
            name='acompanhamento_creas',
            field=models.ManyToManyField(blank=True, null=True, to='prontuario.acompanhamentocreas', verbose_name='AcompanhamentoCreas'),
        ),
    ]
