# Generated by Django 5.2.7 on 2026-02-23 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0048_alter_situacaoviolencia_acompanhamento_creas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcolhimentoFamiliar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('motivo', models.CharField(max_length=250, verbose_name='Motivo principal do acolhimento')),
                ('detalhe', models.TextField(blank=True, max_length=600, null=True, verbose_name='Detalhemento/Contexto')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.membrocomposicao')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', unique=True, verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Acolhimento Famíliar',
                'verbose_name_plural': 'Acolhimentos Familiares',
            },
        ),
        migrations.CreateModel(
            name='AcolhimentoInstitucional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('perda_domicilio', models.TextField(blank=True, max_length=600, null=True, verbose_name='Perda de Domícilio')),
                ('guarda_terceiros', models.TextField(blank=True, max_length=600, null=True, verbose_name='Criança/Adolescente sob guarda de terceiros')),
                ('adulto_prisional', models.BooleanField(blank=True, null=True, verbose_name='Algum membro adulto está em instituição prisional')),
                ('adolescente_internacao', models.BooleanField(blank=True, null=True, verbose_name='Algum adolescente cumpre medida socioeducativa de internação.')),
                ('observacao', models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações Finais')),
                ('acolhimento_familiar', models.ManyToManyField(to='prontuario.acolhimentofamiliar', verbose_name='Acolhimento Familiar')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', unique=True, verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Acolhimento Institucional',
                'verbose_name_plural': 'Acolhimentos Institucionais',
            },
        ),
    ]
