# Generated by Django 5.2.7 on 2026-02-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0049_acolhimentofamiliar_acolhimentoinstitucional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acolhimentoinstitucional',
            name='acolhimento_familiar',
            field=models.ManyToManyField(blank=True, null=True, to='prontuario.acolhimentofamiliar', verbose_name='Acolhimento Familiar'),
        ),
    ]
