# Generated by Django 5.2.7 on 2026-02-24 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0051_alter_membrocomposicao_parentesco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacaoPlanejamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('anotacao', models.TextField(max_length=600, verbose_name='Anotação de Planejamento')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', unique=True, verbose_name='Prontuário')),
                ('tecnico_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Técnico responsável')),
            ],
            options={
                'verbose_name': 'Anotação de Planejamento',
                'verbose_name_plural': 'Anotações de Planejamentos',
            },
        ),
    ]
