# Generated by Django 5.2.7 on 2026-02-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0052_anotacaoplanejamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convivenviafortalecimento',
            name='unidade_inicial',
        ),
        migrations.AddField(
            model_name='convivenviafortalecimento',
            name='unidade_realizacao',
            field=models.CharField(blank=True, choices=[('PROPRIA', '1 - Nesta própria unidade'), ('OUTRA_PUBLICA', '2 - Em outra Unidade Pública da rede Socioassistencial'), ('PRIVADA', '3 - Em unidade/entidade privada da rede socioassistencial'), ('EDUCACAO', '4 - Em unidade de rede de educação'), ('VINCULADA', '9 - Outra unidade vinculada a outras políticas')], null=True, verbose_name='Unidade de realização'),
        ),
    ]
