# Generated by Django 5.2.7 on 2026-02-24 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0053_remove_convivenviafortalecimento_unidade_inicial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovoIngresso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_ingresso', models.DateField(verbose_name='Data de Ingresso')),
                ('motivo', models.CharField(max_length=250, verbose_name='Motivo/Forma de ingresso')),
                ('observacoes', models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações do Ingresso')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', unique=True, verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Novo Ingresso',
                'verbose_name_plural': 'Novos Ingressos',
            },
        ),
    ]
