# Generated by Django 5.2.7 on 2026-02-24 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0055_registrodesligamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodesligamento',
            name='motivo',
            field=models.CharField(choices=[('METAS', '1 - Avaliação Técnica (Metas atingidas)'), ('EVASAO', '2 - Evasão ou recusa da família'), ('MUDANCA', '3 - Mudança de município'), ('OUTRO', '4 - Outros (Especificar em obs)')], max_length=250, verbose_name='Motivo do Desligamento'),
        ),
        migrations.CreateModel(
            name='EvolucaoAcompanhamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('anotacao_acompanhamento', models.ManyToManyField(blank=True, null=True, to='prontuario.anotacaoplanejamento', verbose_name='Anotação de Acompanhamento')),
                ('novo_ingresso', models.ManyToManyField(blank=True, null=True, to='prontuario.novoingresso', verbose_name='Novos Ingressos')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', unique=True, verbose_name='Prontuário')),
                ('registros_desligamentos', models.ManyToManyField(blank=True, null=True, to='prontuario.registrodesligamento', verbose_name='Registros de Desligamentos')),
            ],
            options={
                'verbose_name': 'Evolução do Acompanhamento',
                'verbose_name_plural': 'Evoluções do Acompanhamento',
            },
        ),
    ]
