# Generated by Django 5.2.7 on 2026-02-24 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0056_alter_registrodesligamento_motivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoAcompanhamentoFamiliar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ofertas_assistencia', models.CharField(blank=True, choices=[('SIM', 'Sim, integraumente'), ('PARCIALMENTE', 'Parcialmente'), ('NAO', 'Não foram disponibilizadas')], max_length=150, null=True, verbose_name='Ofertas da Assistência Social')),
                ('encaminhamentos', models.CharField(blank=True, choices=[('SIM', 'Sim, houve resolutividade'), ('PARCIAL', 'Resolutividade parcial'), ('SEM', 'Sem Resolutividade'), ('NAO', 'Não houve necessidade de rede')], max_length=150, null=True, verbose_name='Encaminhamentos para Rede')),
                ('vinculo_familia', models.CharField(blank=True, choices=[('SIM', 'Sim, reconhece e deseja continuar'), ('PARCIALMENTE', 'Reconhece parcialmente'), ('NAO', 'Não reconhece a contribuição')], max_length=150, null=True, verbose_name='Vínculo Família-Serviço')),
                ('status', models.CharField(blank=True, choices=[('PIORA', 'Houve agravamento/piora'), ('EQUIVALENTE', 'Situação equivalente(sem avanços)'), ('AVANCO', 'Houve avanço/melhoria'), ('SIGNIFICATIVO', 'Avanço significativo (Sugere desligamento)')], max_length=150, null=True, verbose_name='Status de Vunerabilidade')),
                ('analise', models.TextField(blank=True, max_length=600, null=True, verbose_name='Análise Descritiva dos Resultados')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', unique=True, verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Avaliação Acompanhamento Famíliar',
                'verbose_name_plural': 'Avaliações Acompanhamento Familiares',
            },
        ),
    ]
