# Generated by Django 5.2.7 on 2026-02-24 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0057_avaliacaoacompanhamentofamiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acolhimentofamiliar',
            name='prontuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário'),
        ),
    ]
