# Generated by Django 5.2.7 on 2026-02-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0058_alter_acolhimentofamiliar_prontuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficioseventuais',
            name='observacao',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações e Justificativa Técnica'),
        ),
        migrations.AlterField(
            model_name='condicaoeducacional',
            name='observacao_geral',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações gerais da Família'),
        ),
        migrations.AlterField(
            model_name='condicaoeducacionalmembro',
            name='observacao',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações sobre a Condição Educacional do Membro'),
        ),
        migrations.AlterField(
            model_name='condicaohabitacional',
            name='outras_observacoes',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Outras observações referentes ao diagnóstico das condições habitacionais da família'),
        ),
        migrations.AlterField(
            model_name='condicoesdesaude',
            name='observacoes',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Outras observações Técnicas'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='outras_observacoes',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Outras observações referentes ao diagnóstico das condições de convivência familiar e comunitária'),
        ),
        migrations.AlterField(
            model_name='exclusaomembrocomposicao',
            name='motivo',
            field=models.TextField(max_length=600, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='pessoareferencia',
            name='razoes',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Razões, demandas ou necessidades do primeiro encaminhamento'),
        ),
        migrations.AlterField(
            model_name='saudecuidadosmembro',
            name='medicamentos',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Medicamentos em uso'),
        ),
        migrations.AlterField(
            model_name='saudecuidadosmembro',
            name='tratamentos',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Tratamentos atuais'),
        ),
        migrations.AlterField(
            model_name='situacaoviolencia',
            name='observacao',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações do Diagnóstico de Violência'),
        ),
        migrations.AlterField(
            model_name='trabalhorendimento',
            name='parecer',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Diagnóstico Situacional'),
        ),
    ]
