# Generated by Django 5.2.7 on 2026-02-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0059_alter_beneficioseventuais_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acolhimentoinstitucional',
            name='observacao',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='avaliacaoacompanhamentofamiliar',
            name='ofertas_assistencia',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim, integralmente'), ('PARCIALMENTE', 'Parcialmente'), ('NAO', 'Não foram disponibilizadas')], max_length=150, null=True, verbose_name='Ofertas da Assistência Social'),
        ),
        migrations.AlterField(
            model_name='beneficioseventuais',
            name='observacao',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='condicaoeducacional',
            name='observacao_geral',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='condicaoeducacionalmembro',
            name='observacao',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='condicaohabitacional',
            name='outras_observacoes',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='condicoesdesaude',
            name='observacoes',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='outras_observacoes',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='novoingresso',
            name='observacoes',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='registrodesligamento',
            name='observacoes',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='situacaoviolencia',
            name='observacao',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações'),
        ),
    ]
