# Generated by Django 5.2.7 on 2026-02-27 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prontuario", "0060_alter_acolhimentoinstitucional_observacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exclusaomembrocomposicao",
            name="membro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exclusoes",
                to="prontuario.membrocomposicao",
            ),
        ),
    ]
