# Generated by Django 5.2.7 on 2026-02-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prontuario", "0061_alter_exclusaomembrocomposicao_membro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exclusaomembrocomposicao",
            name="membro",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Membro",
            ),
        ),
    ]
