# Generated by Django 5.2.7 on 2026-03-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0063_exclusaomembrocomposicao_prontuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentocreas',
            name='data_final',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final'),
        ),
    ]
