# Generated by Django 5.2.7 on 2026-03-20 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0064_alter_acompanhamentocreas_data_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaSocioEducativaMembro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_medida', models.CharField(choices=[('ADVERTENCIA', 'Advertência'), ('REPARAR_DANO', 'Obrigação de reparar dano'), ('PRESTACAO_SERVICOS', 'Prestação de serviços a comunidade'), ('LIBERDADE_ASSISTIDA', 'Liberdade assistida'), ('SEMILIBERDADE', 'Inserção em regime de semiliberdade'), ('ESTABELECIMENTO_EDUCACIONAL', 'Internação em estabelecimento educacional'), ('QUALQUER', 'Qualquer uma das medidas protetivas')], max_length=200, verbose_name='Tipo de Medida')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='Data Término')),
                ('numero_processo', models.CharField(max_length=200, verbose_name='Número do processo')),
                ('membro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.membrocomposicao', unique=True, verbose_name='Membro Composição')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Condição de Saúde do Membro',
                'verbose_name_plural': 'Condições de Saúde dos Membros',
            },
        ),
    ]
