# Generated by Django 5.2.7 on 2026-03-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0065_medidasocioeducativamembro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medidasocioeducativamembro',
            options={'verbose_name': 'Medida Socio Educativa Membro', 'verbose_name_plural': 'Medidas Socio Educativas Membros'},
        ),
    ]
