# Generated by Django 5.2.7 on 2026-03-20 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0066_alter_medidasocioeducativamembro_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidasocioeducativamembro',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.membrocomposicao', verbose_name='Membro Composição'),
        ),
    ]
