# Generated by Django 5.2.7 on 2026-03-20 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0067_alter_medidasocioeducativamembro_membro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidasocioeducativamembro',
            name='membro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.membrocomposicao', unique=True, verbose_name='Membro Composição'),
        ),
        migrations.CreateModel(
            name='AcompanhamentoLAPSC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('acompanhado', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=10, null=True, verbose_name='Acompanhado pelo CRAS')),
                ('data_anotacao', models.DateField(blank=True, null=True, verbose_name='Data da anotação')),
                ('observação', models.TextField(blank=True, max_length=900, null=True, verbose_name='Observação')),
                ('membro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.medidasocioeducativamembro', unique=True, verbose_name='Membro Composição')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Acompanhamento LA PSC',
                'verbose_name_plural': 'Acompanhamentos LA PSC',
            },
        ),
        migrations.CreateModel(
            name='MedidaSocioEducativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('contatos_PSC', models.TextField(blank=True, max_length=600, null=True, verbose_name='Contatos Relativos a PSC')),
                ('acompanhamento_LAPSC_membro', models.ManyToManyField(blank=True, null=True, to='prontuario.acompanhamentolapsc', verbose_name='Membro Acompanhamento')),
                ('membro_socio_educativo', models.ManyToManyField(blank=True, null=True, to='prontuario.medidasocioeducativamembro', verbose_name='Membro SocioEducativo')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', unique=True, verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Medida Socio Educativa',
                'verbose_name_plural': 'Medidas Socio Educativas',
            },
        ),
    ]
