# Generated by Django 5.2.7 on 2026-03-23 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0068_alter_medidasocioeducativamembro_membro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacaoplanejamento',
            name='prontuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário'),
        ),
    ]
