# Generated by Django 5.2.7 on 2026-03-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0069_alter_anotacaoplanejamento_prontuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidasocioeducativamembro',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Início'),
        ),
        migrations.AlterField(
            model_name='medidasocioeducativamembro',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Número do processo'),
        ),
        migrations.AlterField(
            model_name='medidasocioeducativamembro',
            name='tipo_medida',
            field=models.CharField(blank=True, choices=[('ADVERTENCIA', 'Advertência'), ('REPARAR_DANO', 'Obrigação de reparar dano'), ('PRESTACAO_SERVICOS', 'Prestação de serviços a comunidade'), ('LIBERDADE_ASSISTIDA', 'Liberdade assistida'), ('SEMILIBERDADE', 'Inserção em regime de semiliberdade'), ('ESTABELECIMENTO_EDUCACIONAL', 'Internação em estabelecimento educacional'), ('QUALQUER', 'Qualquer uma das medidas protetivas')], max_length=200, null=True, verbose_name='Tipo de Medida'),
        ),
    ]
