# Generated by Django 5.2.7 on 2026-03-30 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0070_alter_medidasocioeducativamembro_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novoingresso',
            name='prontuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário'),
        ),
        migrations.AlterField(
            model_name='registrodesligamento',
            name='prontuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Prontuário'),
        ),
    ]
