# Generated by Django 5.2.7 on 2026-04-06 12:07

import datetime
import prontuario.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0071_alter_novoingresso_prontuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficioseventuais',
            name='data_beneficio',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data do Benéficio'),
        ),
        migrations.AlterField(
            model_name='trabalhorendimentomembro',
            name='qualificacao_profissional',
            field=models.JSONField(blank=True, default=list, validators=[prontuario.validators.validate_qualificacoes], verbose_name='Qualificação Profissional'),
        ),
    ]
