# Generated by Django 5.2.7 on 2026-04-16 11:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0073_alter_condicaoeducacionalmembro_escolaridade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiosservicos',
            options={'verbose_name': 'Benefício e Serviço', 'verbose_name_plural': 'Benefícios e Serviços'},
        ),
        migrations.AlterModelOptions(
            name='pessoareferencia',
            options={'verbose_name': 'Pessoa de Referência', 'verbose_name_plural': 'Pessoas de Referências'},
        ),
        migrations.AlterField(
            model_name='acolhimentofamiliar',
            name='detalhe',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Detalhamento/Contexto'),
        ),
        migrations.AlterField(
            model_name='acolhimentofamiliar',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.membrocomposicao', verbose_name='Membro da Família'),
        ),
        migrations.AlterField(
            model_name='acolhimentoinstitucional',
            name='guarda_terceiros',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Descrição da situação de Criança/Adolescente sob guarda de terceiros'),
        ),
        migrations.AlterField(
            model_name='acolhimentoinstitucional',
            name='observacao',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações finais do Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='acolhimentoinstitucional',
            name='perda_domicilio',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Descrição da Perda de Domícilio (Catástrofe ou Fatalidade)'),
        ),
        migrations.AlterField(
            model_name='avaliacaoacompanhamentofamiliar',
            name='analise',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Descreva os principais ganhos, potencialidades desenvolvidas e fatores que dificultaram o processo.'),
        ),
        migrations.AlterField(
            model_name='avaliacaoacompanhamentofamiliar',
            name='encaminhamentos',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim, houve resolutividade'), ('PARCIAL', 'Resolutividade parcial'), ('SEM', 'Sem Resolutividade'), ('NAO', 'Não houve necessidade de rede')], max_length=150, null=True, verbose_name='Em relação aos encaminhamentos da família/indivíduo para demais políticas, houve atendimento efetivo e resolutivo por parte da área que recebeu o encaminhamento'),
        ),
        migrations.AlterField(
            model_name='avaliacaoacompanhamentofamiliar',
            name='ofertas_assistencia',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim, integralmente'), ('PARCIALMENTE', 'Parcialmente'), ('NAO', 'Não foram disponibilizadas')], max_length=150, null=True, verbose_name='Foram efetivamente disponibilizadas para a família/indivíduo todas as ofertas da Assistência Social cuja necessidade havia sido identificada pelo profissional'),
        ),
        migrations.AlterField(
            model_name='avaliacaoacompanhamentofamiliar',
            name='status',
            field=models.CharField(blank=True, choices=[('PIORA', 'Houve agravamento/piora'), ('EQUIVALENTE', 'Situação equivalente(sem avanços)'), ('AVANCO', 'Houve avanço/melhoria'), ('SIGNIFICATIVO', 'Avanço significativo (Sugere desligamento)')], max_length=150, null=True, verbose_name='Como você classifica os resultados obtidos quanto a ampliação da capacidade de enfrentamento ou superação das condições de vulnerabilidade e risco social e pessoal'),
        ),
        migrations.AlterField(
            model_name='avaliacaoacompanhamentofamiliar',
            name='vinculo_familia',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim, reconhece e deseja continuar'), ('PARCIALMENTE', 'Reconhece parcialmente'), ('NAO', 'Não reconhece a contribuição')], max_length=150, null=True, verbose_name='A família reconhece o Serviço de Acompanhamento como algo que contribui para o enfrentamento de seus problemas e dificuldades e deseja continuar recebendo atenções deste serviço'),
        ),
        migrations.AlterField(
            model_name='beneficioseventuais',
            name='data_beneficio',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data do Benefício'),
        ),
        migrations.AlterField(
            model_name='beneficioseventuais',
            name='observacao',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações e Justificativa Técnica'),
        ),
        migrations.AlterField(
            model_name='beneficiosservicos',
            name='convivencia_e_fortalecimento',
            field=models.ManyToManyField(blank=True, null=True, to='prontuario.convivenviafortalecimento', verbose_name='Convivência e Fortalecimento de Vínculos'),
        ),
        migrations.AlterField(
            model_name='condicaoeducacional',
            name='observacao_geral',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações gerais da família'),
        ),
        migrations.AlterField(
            model_name='condicaoeducacionalmembro',
            name='frequencia',
            field=models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular'), ('NAO_FREQUENTA', 'Não Frequenta'), ('EVADIDO', 'Evadido')], max_length=150, null=True, verbose_name='Frequência Escolar'),
        ),
        migrations.AlterField(
            model_name='condicaoeducacionalmembro',
            name='observacao',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações do membro'),
        ),
        migrations.AlterField(
            model_name='condicaohabitacional',
            name='abastecimento_agua',
            field=models.CharField(blank=True, choices=[('REDE', 'Rede geral de distribuição'), ('POCO', 'Poço, ou Nascente'), ('CISTERNA', 'Cisterna de captação'), ('CARRO', 'Carro Pipa'), ('OUTRA', 'Outra forma')], null=True, verbose_name='Forma de Abastecimento de água'),
        ),
        migrations.AlterField(
            model_name='condicaohabitacional',
            name='area_conflito',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=10, null=True, verbose_name='O domicílio está localizado em área com conflito/violência?'),
        ),
        migrations.AlterField(
            model_name='condicaohabitacional',
            name='area_risco',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=10, null=True, verbose_name='O domicílio está localizado em área de risco (desabamento/alagamento)?'),
        ),
        migrations.AlterField(
            model_name='condicaohabitacional',
            name='dificil_acesso',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=10, null=True, verbose_name='O domicílio está em área de difícil acesso geográfico?'),
        ),
        migrations.AlterField(
            model_name='condicaohabitacional',
            name='esgotamento',
            field=models.CharField(blank=True, choices=[('REDE_COLETORA', 'Rede coletora/ esgoto/ pluvial'), ('SEPTICA', 'Fossa séptica'), ('RUDIMENTAR', 'Fossa rudimentar'), ('DIRETO', 'Direto para rio/ lago/ mar'), ('SEM_BANHEIRO', 'Domicílio sem banheiro')], max_length=150, null=True, verbose_name='Escoamento sanitário'),
        ),
        migrations.AlterField(
            model_name='condicaohabitacional',
            name='locomocao',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=10, null=True, verbose_name='O domicílio possui acessibilidade para pessoas com dificuldade de locomoção'),
        ),
        migrations.AlterField(
            model_name='condicaohabitacional',
            name='media_dormitorios',
            field=models.IntegerField(blank=True, null=True, verbose_name='Média de pessoas por dormitório'),
        ),
        migrations.AlterField(
            model_name='condicaohabitacional',
            name='outras_observacoes',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações referentes às condições habitacionais da família'),
        ),
        migrations.AlterField(
            model_name='condicaohabitacional',
            name='total_comodos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Número total de cômodos do domicílio'),
        ),
        migrations.AlterField(
            model_name='condicaohabitacional',
            name='total_dormitorios',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Número total de cômodos utilizados como dormitórios'),
        ),
        migrations.AlterField(
            model_name='condicoesdesaude',
            name='inseguranca_alimentar',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='A família declara ou há indícios de insegurança alimentar por insuficiência de alimentos'),
        ),
        migrations.AlterField(
            model_name='condicoesdesaude',
            name='observacoes',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Outras observações técnicas (Diagnóstico de Saúde)'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='atividade_lazer_crianca',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Criança ou adolescente sem acesso a lazer, recreação e convívio social?'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='atividade_lazer_idoso',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Idoso sem acesso a lazer, recreação e convívio social?'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='bairro',
            field=models.BooleanField(blank=True, null=True, verbose_name='A família sempre morou no bairro'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='companhia_adulto',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Dependentes (crianças, idosos ou PcD) permanecem sozinhos sem acompanhante adulto?'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='conflitos_conjugais',
            field=models.CharField(blank=True, choices=[('COM_VIOLENCIA', 'Conflituoso, com violência'), ('SEM_VIOLENCIA', 'Conflituoso, sem violência'), ('SEM_CONFLICO', 'Sem conflitos relevantes')], null=True, verbose_name='Avaliação de Convivência e Conflitos nas relações conjugais'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='conflitos_irmaos',
            field=models.CharField(blank=True, choices=[('COM_VIOLENCIA', 'Conflituoso, com violência'), ('SEM_VIOLENCIA', 'Conflituoso, sem violência'), ('SEM_CONFLICO', 'Sem conflitos relevantes')], null=True, verbose_name='Avaliação de Convivência e Conflitos nas relações entre irmãos'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='conflitos_outros',
            field=models.CharField(blank=True, choices=[('COM_VIOLENCIA', 'Conflituoso, com violência'), ('SEM_VIOLENCIA', 'Conflituoso, sem violência'), ('SEM_CONFLICO', 'Sem conflitos relevantes')], null=True, verbose_name='Avaliação de Convivência e Conflitos nas relações envolvendo outros indivíduos que residam no domicílio'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='conflitos_responsaveis',
            field=models.CharField(blank=True, choices=[('COM_VIOLENCIA', 'Conflituoso, com violência'), ('SEM_VIOLENCIA', 'Conflituoso, sem violência'), ('SEM_CONFLICO', 'Sem conflitos relevantes')], null=True, verbose_name='Avaliação de Convivência e Conflitos nas relações entre pais e filhos'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='estado',
            field=models.BooleanField(blank=True, null=True, verbose_name='A família sempre morou no estado'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='grupo_religioso',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Participa de grupos religiosos ou comunitários?'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='movimento_social',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Participa de movimentos sociais, sindicatos ou defesa de interesses coletivos?'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='municipio',
            field=models.BooleanField(blank=True, null=True, verbose_name='A família sempre morou no município'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='outras_observacoes',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Parecer Técnico Consolidado'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='parente_proximo',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Possui parentes próximos que integram rede de apoio?'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='vitima_ameaca',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Vítima de ameaça ou discriminação na comunidade?'),
        ),
        migrations.AlterField(
            model_name='convivenciafamiliar',
            name='vizinhos_apoio',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Possui vizinhos que constituam rede de solidariedade?'),
        ),
        migrations.AlterField(
            model_name='descumprimentocondicionalidadesbolsa',
            name='efeito_codigo',
            field=models.CharField(choices=[('ADVERTENCIA', '01 - Advertência'), ('BLOQUEIO', '02 - Bloqueio'), ('SUSPENSAO', '03 - Suspensão'), ('CANCELAMENTO', '04 - Cancelamento')], max_length=150, verbose_name='Código Efeito'),
        ),
        migrations.AlterField(
            model_name='descumprimentoeducacional',
            name='efeito_codigo',
            field=models.CharField(choices=[('ADVERTENCIA', '01 - Advertência'), ('BLOQUEIO', '02 - Bloqueio'), ('SUSPENSAO', '03 - Suspensão'), ('CANCELAMENTO', '04 - Cancelamento')], max_length=150, verbose_name='Efeito gerado (código)'),
        ),
        migrations.AlterField(
            model_name='descumprimentoeducacional',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prontuario.membrocomposicao', verbose_name='Membro da família'),
        ),
        migrations.AlterField(
            model_name='evolucaoacompanhamento',
            name='anotacao_acompanhamento',
            field=models.ManyToManyField(blank=True, null=True, to='prontuario.anotacaoplanejamento', verbose_name='Nova Anotação de Planejamento'),
        ),
        migrations.AlterField(
            model_name='medidasocioeducativa',
            name='contatos_PSC',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Registros dos contatos do local de prestação e do orientador responsável'),
        ),
        migrations.AlterField(
            model_name='medidasocioeducativamembro',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='medidasocioeducativamembro',
            name='data_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='medidasocioeducativamembro',
            name='tipo_medida',
            field=models.CharField(blank=True, choices=[('ADVERTENCIA', 'Advertência'), ('REPARAR_DANO', 'Obrigação de reparar dano'), ('PRESTACAO_SERVICOS', 'Prestação de serviços a comunidade'), ('LIBERDADE_ASSISTIDA', 'Liberdade assistida'), ('SEMILIBERDADE', 'Inserção em regime de semiliberdade'), ('ESTABELECIMENTO_EDUCACIONAL', 'Internação em estabelecimento educacional'), ('QUALQUER', 'Qualquer uma das medidas protetivas')], max_length=200, null=True, verbose_name='Tipo de Medida Socio Educativa'),
        ),
        migrations.AlterField(
            model_name='novoingresso',
            name='motivo',
            field=models.CharField(max_length=250, verbose_name='Motivo/Forma de Ingresso'),
        ),
        migrations.AlterField(
            model_name='novoingresso',
            name='observacoes',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações do Ingresso'),
        ),
        migrations.AlterField(
            model_name='pessoareferencia',
            name='beneficio',
            field=models.ManyToManyField(blank=True, null=True, to='prontuario.beneficiosocial', verbose_name='Benefícios Sociais'),
        ),
        migrations.AlterField(
            model_name='pessoareferencia',
            name='contato_encaminhamento',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Contato do órgão/unidade'),
        ),
        migrations.AlterField(
            model_name='pessoareferencia',
            name='especifidade_familia',
            field=models.CharField(blank=True, choices=[('SITUACAO_RUA', 'Família/pessoa em situação de rua'), ('RIBEIRINHA', 'Família ribeirinha'), ('ALDEIA', 'Família indígina residente em aldeia/reserva'), ('QUILOMBOLA', 'Família quilombola'), ('CIGANA', 'Família cigana'), ('INDIGINA_NAO_RESIDENTE', 'Família indígena não residente em aldeia/reserva')], max_length=150, null=True, verbose_name='Especifidade étnico-culturais'),
        ),
        migrations.AlterField(
            model_name='pessoareferencia',
            name='forma_ingresso',
            field=models.CharField(blank=True, choices=[('ESPONTANEA', 'Demanda Espontânea'), ('ATIVA', 'Busca Ativa'), ('PROTECAO_BASICA', 'Encaminhamento Proteção Social Básica'), ('PROTECAO_ESPECIal', 'Encaminhamento Proteção Social Especial'), ('SAUDE', 'Encaminhamento pela Saúde'), ('EDUCAÇÃO', 'Encaminhado pela Educação'), ('SETORIAIS', 'Outras políticas setoriais'), ('CONSELHO', 'Conselho Tutelar'), ('JUDICIARIO', 'Poder Judiciário'), ('DIREITOS', 'Sistema de Garantia de Direitos'), ('OUTROS', 'Outros Encaminhamentos')], null=True, verbose_name='Forma de ingresso'),
        ),
        migrations.AlterField(
            model_name='pessoareferencia',
            name='razoes',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Motivo do atendimento'),
        ),
        migrations.AlterField(
            model_name='registrodesligamento',
            name='observacoes',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações do Desligamento'),
        ),
        migrations.AlterField(
            model_name='saudecuidadosmembro',
            name='acompanhamento',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Realiza Acompanhamento Médico?'),
        ),
        migrations.AlterField(
            model_name='saudecuidadosmembro',
            name='alcool',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Uso abusivo de Álcool?'),
        ),
        migrations.AlterField(
            model_name='saudecuidadosmembro',
            name='cuidados_terceiros',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Necessita de cuidados constantes de terceiros?'),
        ),
        migrations.AlterField(
            model_name='saudecuidadosmembro',
            name='doencas_graves',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Doenças Graves e/ou Crônicas'),
        ),
        migrations.AlterField(
            model_name='saudecuidadosmembro',
            name='drogas',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Uso abusivo de Drogas?'),
        ),
        migrations.AlterField(
            model_name='saudecuidadosmembro',
            name='remedio',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Uso de remédios controlados?'),
        ),
        migrations.AlterField(
            model_name='situacaoviolencia',
            name='negligencia',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Alguma criança da família sofreu negligência'),
        ),
        migrations.AlterField(
            model_name='situacaoviolencia',
            name='observacao',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações do Diagnóstico de Violência'),
        ),
        migrations.AlterField(
            model_name='situacaoviolencia',
            name='situacao_trabalho_rua',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Membro da família em situação de trabalho na rua'),
        ),
        migrations.AlterField(
            model_name='situacaoviolencia',
            name='trabalho_infantil',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], null=True, verbose_name='Membro da família em situação de trabalho infantil'),
        ),
        migrations.AlterField(
            model_name='trabalhorendimento',
            name='renda_per_capita',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda familiar per capita (Sem Benefícios)'),
        ),
        migrations.AlterField(
            model_name='trabalhorendimento',
            name='renda_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda total da família (Sem Benefícios)'),
        ),
        migrations.AlterField(
            model_name='trabalhorendimento',
            name='transferencia_renda_familia',
            field=models.ManyToManyField(blank=True, null=True, to='prontuario.transferenciarenda', verbose_name='Benefícios sociais recebidos pela família'),
        ),
        migrations.AlterField(
            model_name='trabalhorendimentomembro',
            name='carteira_assinada',
            field=models.BooleanField(blank=True, null=True, verbose_name='Possui Carteira de Trabalho'),
        ),
        migrations.AlterField(
            model_name='trabalhorendimentomembro',
            name='renda_individual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda Individual (sem benefícios sociais)'),
        ),
        migrations.AlterField(
            model_name='transferenciarenda',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do benefício'),
        ),
    ]
