# Generated by Django 5.2.7 on 2026-04-16 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadaos', '0009_alter_cidadao_orgao_emissor_alter_cidadao_uf_rg'),
        ('prontuario', '0074_alter_beneficiosservicos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrocomposicao',
            name='cidadao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composicoes', to='cidadaos.cidadao'),
        ),
    ]
