# Generated by Django 5.2.7 on 2026-04-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0075_alter_membrocomposicao_cidadao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrocomposicao',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('REFERENCIA', 'Pessoa de Referência'), ('CONJUGE', 'Cônjuge/Companheiro(a)'), ('FILHO', 'Filho(a)'), ('ENTEADO', 'Enteado(a)'), ('BISNETO', 'Bisneto(a)'), ('SOGRO', 'Sogro(a)'), ('GENRO', 'Genro'), ('NORA', 'Nora'), ('NAO_PARENTE', 'Não Parente'), ('AVO', 'AVÔ/AVÓ'), ('PAI', 'Pai'), ('MAE', 'Mãe'), ('NETO', 'Neto(a)'), ('IRMAO_IRMA', 'Irmão/Irmã'), ('OUTRO', 'Outro')], null=True, verbose_name='Parentesco'),
        ),
    ]
