# Generated by Django 5.2.7 on 2026-06-10 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0021_chamadapainel'),
        ('cidadaos', '0009_alter_cidadao_orgao_emissor_alter_cidadao_uf_rg'),
        ('prontuario', '0076_alter_membrocomposicao_parentesco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrocomposicao',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('REFERENCIA', 'Pessoa de Referência'), ('CONJUGE', 'Cônjuge/Companheiro(a)'), ('FILHO', 'Filho(a)'), ('ENTEADO', 'Enteado(a)'), ('BISNETO', 'Bisneto(a)'), ('SOGRO', 'Sogro(a)'), ('GENRO', 'Genro'), ('NORA', 'Nora'), ('NAO_PARENTE', 'Não Parente'), ('AVO', 'AVÓ/AVÔ'), ('PAI', 'Pai'), ('MAE', 'Mãe'), ('NETO', 'Neto(a)'), ('IRMAO_IRMA', 'Irmão/Irmã'), ('OUTRO', 'Outro')], null=True, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='pessoareferencia',
            name='especifidade_familia',
            field=models.CharField(blank=True, choices=[('SITUACAO_RUA', 'Família/pessoa em situação de rua'), ('RIBEIRINHA', 'Família ribeirinha'), ('ALDEIA', 'Família indígena residente em aldeia/reserva'), ('QUILOMBOLA', 'Família quilombola'), ('CIGANA', 'Família cigana'), ('INDIGINA_NAO_RESIDENTE', 'Família indígena não residente em aldeia/reserva')], max_length=150, null=True, verbose_name='Especifidade étnico-culturais'),
        ),
        migrations.AlterField(
            model_name='pessoareferencia',
            name='forma_ingresso',
            field=models.CharField(blank=True, choices=[('ESPONTANEA', 'Demanda Espontânea'), ('ATIVA', 'Busca Ativa'), ('PROTECAO_BASICA', 'Encaminhamento Proteção Social Básica'), ('PROTECAO_ESPECIAL', 'Encaminhamento Proteção Social Especial'), ('SAUDE', 'Encaminhamento pela Saúde'), ('EDUCACAO', 'Encaminhado pela Educação'), ('SETORIAIS', 'Outras políticas setoriais'), ('CONSELHO', 'Conselho Tutelar'), ('JUDICIARIO', 'Poder Judiciário'), ('DIREITOS', 'Sistema de Garantia de Direitos'), ('OUTROS', 'Outros Encaminhamentos')], null=True, verbose_name='Forma de ingresso'),
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('diagnostico', models.TextField(blank=True, max_length=600, null=True, verbose_name='Diagnóstico')),
                ('observacoes', models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='agendamentos.agendamento', verbose_name='Agendamento')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='cidadaos.cidadao', verbose_name='Cidadão')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receitas_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ReceitaMedicamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='Medicamento')),
                ('dosagem', models.CharField(max_length=100, verbose_name='Dosagem')),
                ('frequencia', models.CharField(max_length=100, verbose_name='Frequência')),
                ('duracao', models.CharField(max_length=100, verbose_name='Duração')),
                ('instrucoes', models.TextField(blank=True, max_length=600, null=True, verbose_name='Instruções')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='prontuario.receita', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Medicamento da Receita',
                'verbose_name_plural': 'Medicamentos da Receita',
            },
        ),
    ]
