# Generated by Django 5.2.7 on 2026-09-28 21:32

from datetime import timedelta

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def preencher_data_validade(apps, schema_editor):
    Receita = apps.get_model("prontuario", "Receita")
    for receita in Receita.objects.filter(data_validade__isnull=True).only("id", "data_emissao", "validade_dias"):
        emissao = timezone.localtime(receita.data_emissao).date()
        receita.data_validade = emissao + timedelta(days=receita.validade_dias)
        receita.save(update_fields=["data_validade"])


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0004_permissoes_estoque'),
        ('prontuario', '0077_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='data_validade',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Válida até'),
        ),
        migrations.AddField(
            model_name='receita',
            name='validade_dias',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Validade (dias)'),
        ),
        migrations.AddField(
            model_name='receitamedicamento',
            name='medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_receita', to='medicamentos.medicamento', verbose_name='Medicamento'),
        ),
        migrations.AddField(
            model_name='receitamedicamento',
            name='quantidade_dispensada',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade Dispensada'),
        ),
        migrations.AddField(
            model_name='receitamedicamento',
            name='quantidade_prescrita',
            field=models.PositiveIntegerField(blank=True, help_text='Em unidades de dispensação (comprimidos, frascos...). Nulo em itens legados.', null=True, verbose_name='Quantidade Prescrita'),
        ),
        migrations.AddField(
            model_name='receitamedicamento',
            name='status_dispensacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Dispensado parcialmente'), ('DISPENSADO', 'Dispensado')], default='PENDENTE', max_length=20, verbose_name='Status da Dispensação'),
        ),
        migrations.AlterField(
            model_name='receitamedicamento',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Descrição do Medicamento'),
        ),
        migrations.RunPython(preencher_data_validade, migrations.RunPython.noop),
    ]
