# Generated by Django 5.2.7 on 2026-09-28 22:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0022_atendente_grupos_saude'),
        ('cidadaos', '0010_cidadao_dados_clinicos'),
        ('prontuario', '0079_permissoes_receita'),
        ('unidade_posto', '0009_alter_servicounidadeposto_mesmo_expediente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAtendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('classificacao_risco', models.CharField(blank=True, choices=[('VERMELHO', 'Vermelho - Emergência'), ('LARANJA', 'Laranja - Muito urgente'), ('AMARELO', 'Amarelo - Urgente'), ('VERDE', 'Verde - Pouco urgente'), ('AZUL', 'Azul - Não urgente')], max_length=20, null=True, verbose_name='Classificação de Risco')),
                ('queixa_principal', models.TextField(max_length=600, verbose_name='Queixa Principal')),
                ('subjetivo', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Subjetivo (história)')),
                ('objetivo', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Objetivo (exame físico)')),
                ('avaliacao', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Avaliação')),
                ('cid', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[A-Z][0-9]{2}(\\.[0-9A-Z]{1,2})?$', 'Informe um CID-10 válido, ex.: J06.9')], verbose_name='CID-10')),
                ('plano', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Plano / Conduta')),
                ('pressao_sistolica', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)], verbose_name='PA sistólica (mmHg)')),
                ('pressao_diastolica', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)], verbose_name='PA diastólica (mmHg)')),
                ('frequencia_cardiaca', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(250)], verbose_name='Frequência cardíaca (bpm)')),
                ('frequencia_respiratoria', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(80)], verbose_name='Frequência respiratória (irpm)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('30.0')), django.core.validators.MaxValueValidator(Decimal('45.0'))], verbose_name='Temperatura (°C)')),
                ('saturacao_o2', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)], verbose_name='Saturação de O₂ (%)')),
                ('glicemia_capilar', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)], verbose_name='Glicemia capilar (mg/dL)')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.3')), django.core.validators.MaxValueValidator(Decimal('400'))], verbose_name='Peso (kg)')),
                ('altura', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(250)], verbose_name='Altura (cm)')),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='registro_atendimento', to='agendamentos.agendamento', verbose_name='Agendamento')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_atendimento', to='cidadaos.cidadao', verbose_name='Cidadão')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_atendimento', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_atendimento', to='unidade_posto.unidadeposto', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Registro de Atendimento',
                'verbose_name_plural': 'Registros de Atendimento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AbastecimentoAgua',
        ),
        migrations.RemoveField(
            model_name='acolhimentofamiliar',
            name='membro',
        ),
        migrations.RemoveField(
            model_name='acolhimentofamiliar',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='acolhimentoinstitucional',
            name='acolhimento_familiar',
        ),
        migrations.RemoveField(
            model_name='acolhimentoinstitucional',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='acompanhamentocreas',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='situacaoviolencia',
            name='acompanhamento_creas',
        ),
        migrations.RemoveField(
            model_name='acompanhamentolapsc',
            name='membro',
        ),
        migrations.RemoveField(
            model_name='acompanhamentolapsc',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='medidasocioeducativa',
            name='acompanhamento_LAPSC_membro',
        ),
        migrations.RemoveField(
            model_name='anotacaoplanejamento',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='anotacaoplanejamento',
            name='tecnico_responsavel',
        ),
        migrations.RemoveField(
            model_name='evolucaoacompanhamento',
            name='anotacao_acompanhamento',
        ),
        migrations.RemoveField(
            model_name='avaliacaoacompanhamentofamiliar',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='beneficioseventuais',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='beneficiosservicos',
            name='beneficios_eventuais',
        ),
        migrations.RemoveField(
            model_name='transferenciarenda',
            name='beneficio',
        ),
        migrations.RemoveField(
            model_name='pessoareferencia',
            name='beneficio',
        ),
        migrations.RemoveField(
            model_name='beneficiosservicos',
            name='convivencia_e_fortalecimento',
        ),
        migrations.RemoveField(
            model_name='beneficiosservicos',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='condicaoeducacional',
            name='condicao_educacional_membro',
        ),
        migrations.RemoveField(
            model_name='condicaoeducacional',
            name='descumprimento_educacional_membro',
        ),
        migrations.RemoveField(
            model_name='condicaoeducacional',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='condicaoeducacionalmembro',
            name='membro',
        ),
        migrations.RemoveField(
            model_name='condicaoeducacionalmembro',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='condicaohabitacional',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='condicoesdesaude',
            name='condicoes_saude_membro',
        ),
        migrations.RemoveField(
            model_name='condicoesdesaude',
            name='descumprimento_condicionalidade',
        ),
        migrations.RemoveField(
            model_name='condicoesdesaude',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='convivenciafamiliar',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='convivenviafortalecimento',
            name='membro',
        ),
        migrations.RemoveField(
            model_name='convivenviafortalecimento',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='descumprimentocondicionalidadesbolsa',
            name='membro',
        ),
        migrations.RemoveField(
            model_name='descumprimentocondicionalidadesbolsa',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='descumprimentoeducacional',
            name='membro',
        ),
        migrations.RemoveField(
            model_name='descumprimentoeducacional',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='evolucaoacompanhamento',
            name='novo_ingresso',
        ),
        migrations.RemoveField(
            model_name='evolucaoacompanhamento',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='evolucaoacompanhamento',
            name='registros_desligamentos',
        ),
        migrations.RemoveField(
            model_name='exclusaomembrocomposicao',
            name='prontuario',
        ),
        migrations.DeleteModel(
            name='FormaIngresso',
        ),
        migrations.RemoveField(
            model_name='medidasocioeducativa',
            name='membro_socio_educativo',
        ),
        migrations.RemoveField(
            model_name='medidasocioeducativa',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='medidasocioeducativamembro',
            name='membro',
        ),
        migrations.RemoveField(
            model_name='medidasocioeducativamembro',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='membrocomposicao',
            name='cidadao',
        ),
        migrations.RemoveField(
            model_name='membrocomposicao',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='trabalhorendimentomembro',
            name='membro',
        ),
        migrations.RemoveField(
            model_name='saudecuidadosmembro',
            name='membro',
        ),
        migrations.RemoveField(
            model_name='novoingresso',
            name='prontuario',
        ),
        migrations.DeleteModel(
            name='OrgaoOrigemEncaminhamento',
        ),
        migrations.DeleteModel(
            name='Parentesco',
        ),
        migrations.RemoveField(
            model_name='pessoareferencia',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='pessoareferencia',
            name='pessoa_referencia',
        ),
        migrations.RemoveField(
            model_name='pessoareferencia',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='pessoareferencia',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='unidade_inicial',
        ),
        migrations.RemoveField(
            model_name='transferenciarenda',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='trabalhorendimentomembro',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='registrodesligamento',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='trabalhorendimento',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='situacaoviolencia',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='saudecuidadosmembro',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='trabalhorendimento',
            name='trabalho_rendimento_membro',
        ),
        migrations.RemoveField(
            model_name='trabalhorendimento',
            name='transferencia_renda_familia',
        ),
        migrations.DeleteModel(
            name='AcolhimentoFamiliar',
        ),
        migrations.DeleteModel(
            name='AcolhimentoInstitucional',
        ),
        migrations.DeleteModel(
            name='AcompanhamentoCreas',
        ),
        migrations.DeleteModel(
            name='AcompanhamentoLAPSC',
        ),
        migrations.DeleteModel(
            name='AnotacaoPlanejamento',
        ),
        migrations.DeleteModel(
            name='AvaliacaoAcompanhamentoFamiliar',
        ),
        migrations.DeleteModel(
            name='BeneficiosEventuais',
        ),
        migrations.DeleteModel(
            name='BeneficioSocial',
        ),
        migrations.DeleteModel(
            name='BeneficiosServicos',
        ),
        migrations.DeleteModel(
            name='CondicaoEducacional',
        ),
        migrations.DeleteModel(
            name='CondicaoEducacionalMembro',
        ),
        migrations.DeleteModel(
            name='CondicaoHabitacional',
        ),
        migrations.DeleteModel(
            name='CondicoesDeSaude',
        ),
        migrations.DeleteModel(
            name='ConvivenciaFamiliar',
        ),
        migrations.DeleteModel(
            name='ConvivenviaFortalecimento',
        ),
        migrations.DeleteModel(
            name='DescumprimentoCondicionalidadesBolsa',
        ),
        migrations.DeleteModel(
            name='DescumprimentoEducacional',
        ),
        migrations.DeleteModel(
            name='EvolucaoAcompanhamento',
        ),
        migrations.DeleteModel(
            name='ExclusaoMembroComposicao',
        ),
        migrations.DeleteModel(
            name='MedidaSocioEducativa',
        ),
        migrations.DeleteModel(
            name='MedidaSocioEducativaMembro',
        ),
        migrations.DeleteModel(
            name='MembroComposicao',
        ),
        migrations.DeleteModel(
            name='NovoIngresso',
        ),
        migrations.DeleteModel(
            name='PessoaReferencia',
        ),
        migrations.DeleteModel(
            name='Unidade',
        ),
        migrations.DeleteModel(
            name='RegistroDesligamento',
        ),
        migrations.DeleteModel(
            name='SituacaoViolencia',
        ),
        migrations.DeleteModel(
            name='Prontuario',
        ),
        migrations.DeleteModel(
            name='SaudeCuidadosMembro',
        ),
        migrations.DeleteModel(
            name='TrabalhoRendimentoMembro',
        ),
        migrations.DeleteModel(
            name='TrabalhoRendimento',
        ),
        migrations.DeleteModel(
            name='TransferenciaRenda',
        ),
    ]
