# Generated by Django 5.2.7 on 2025-11-13 18:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioHorario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(verbose_name='Data do bloqueio')),
                ('hora_inicio', models.TimeField(verbose_name='Horário de início')),
                ('hora_fim', models.TimeField(verbose_name='Horário de término')),
                ('motivo', models.TextField(verbose_name='Motivo do bloqueio')),
                ('justificativa_alteracao', models.TextField(blank=True, null=True, verbose_name='Justificativa da alteração/remoção')),
            ],
            options={
                'verbose_name': 'Bloqueio de Horário',
                'verbose_name_plural': 'Bloqueios de Horários',
                'ordering': ['-data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ServicoUnidadeCras',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('dias_semana', models.JSONField(default=list, help_text='Selecione os dias (lista de números de 1 a 7).', verbose_name='Dias da Semana de Atendimento')),
                ('mesmo_expediente', models.BooleanField(default=False, verbose_name='Usar expediente padrão do CRAS')),
                ('hora_manha_inicio', models.TimeField(blank=True, null=True, verbose_name='Início Manhã')),
                ('hora_manha_fim', models.TimeField(blank=True, null=True, verbose_name='Fim Manhã')),
                ('hora_tarde_inicio', models.TimeField(blank=True, null=True, verbose_name='Início Tarde')),
                ('hora_tarde_fim', models.TimeField(blank=True, null=True, verbose_name='Fim Tarde')),
            ],
            options={
                'verbose_name': 'Serviço por Unidade CRAS',
                'verbose_name_plural': 'Serviços por Unidade CRAS',
            },
        ),
        migrations.CreateModel(
            name='UnidadeCras',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('logradouro', models.CharField(max_length=150, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('hora_manha_inicio', models.TimeField(null=True, verbose_name='Início Expediente Manhã')),
                ('hora_manha_fim', models.TimeField(null=True, verbose_name='Fim Expediente Manhã')),
                ('hora_tarde_inicio', models.TimeField(blank=True, null=True, verbose_name='Início Expediente Tarde')),
                ('hora_tarde_fim', models.TimeField(blank=True, null=True, verbose_name='Fim Expediente Tarde')),
            ],
            options={
                'verbose_name': 'Unidade Cras',
                'verbose_name_plural': 'Unidades Cras',
            },
        ),
    ]
