# Generated by Django 5.2.7 on 2025-11-26 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade_cras', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guiche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guiches', to='unidade_cras.unidadecras', verbose_name='Unidade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
