# Generated by Django 5.2.7 on 2026-01-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade_cras', '0003_guiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueiohorario',
            name='data_final',
            field=models.DateField(blank=True, null=True, verbose_name='Data final bloqueio'),
        ),
    ]
