# Generated by Django 5.2.7 on 2026-01-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bairro_options'),
        ('unidade_cras', '0004_bloqueiohorario_data_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadecras',
            name='bairros_abrangencia',
            field=models.ManyToManyField(null=True, related_name='bairros_abrangencia', to='app.bairro', verbose_name='Território de Abrangência'),
        ),
    ]
