# Generated by Django 5.2.7 on 2026-02-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade_cras', '0006_unidadecras_latitude_unidadecras_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueiohorario',
            name='justificativa_alteracao',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Justificativa da alteração/remoção'),
        ),
        migrations.AlterField(
            model_name='bloqueiohorario',
            name='motivo',
            field=models.TextField(max_length=600, verbose_name='Motivo do bloqueio'),
        ),
    ]
