# Generated by Django 5.2.7 on 2026-03-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade_cras', '0007_alter_bloqueiohorario_justificativa_alteracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadecras',
            name='nome',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome'),
        ),
    ]
