"""
Django settings for cras project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
from csp.constants import NONCE


load_dotenv()

dotenv_path = os.path.join(os.path.dirname(__file__), "..", ".env")
load_dotenv(dotenv_path, override=True)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"
# DEBUG = True
SECRET_KEY = "django-insecure-z!u-8ii9#-g76gl4m@2w4=moy2cxsa7ndey0t)2$s1-q!p0-i_"


# SECURITY WARNING: don't run with debug turned on in production!

def _split_env_list(value):
    return [item.strip() for item in value.split(",") if item.strip()]


ALLOWED_HOSTS = _split_env_list(os.getenv("ALLOWED_HOSTS", ""))
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["*"] if DEBUG else ["dev-agendamentocras.fortaleza.ce.gov.br"]


SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"


# Application definition

INSTALLED_APPS = [\
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app",
    "servicos",
    "unidade_cras",
    "cidadaos",
    "usuarios",
    "fila_espera",
    "agendamentos",
    "authentication",
    "prontuario",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "corsheaders",
    "atendimento_familiar",
    "django.contrib.postgres",
    "duvidas_frequentes",
    "avaliacao",
    "encaminhamentos",
    "relatorios",
    # "csp",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # 'app.custom_cors_middleware.CustomCorsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "app.core_middleware.PerformanceMiddleware",
    "app.core_middleware.AuditMiddleware",
    # "csp.middleware.CSPMiddleware",
    # "cras.middleware.RequestTimingMiddleware",
]


ROOT_URLCONF = "cras.urls"

if not DEBUG:
    MIDDLEWARE.insert(1, 'app.custom_cors_middleware.CustomCorsMiddleware',)
    MIDDLEWARE.insert(1, "csp.middleware.CSPMiddleware")  # desativado para teste de bloqueio do VLibras
    INSTALLED_APPS.insert(0, "csp")  # desativado para teste de bloqueio do VLibras

    SESSION_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 15768000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    
    X_FRAME_OPTIONS = 'DENY'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "base",
            BASE_DIR / "Frontend" / "dist",
            BASE_DIR / "static",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

AUTH_USER_MODEL = "usuarios.Usuario"


WSGI_APPLICATION = "cras.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

USE_SQLITE = True if os.getenv("USE_SQLITE") in ["True", "true"] else False
ORACLE = os.getenv("ORACLE", "False").lower() == "true"

if USE_SQLITE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
            "OPTIONS": {
                "timeout": 30,
            },
        }
    }
elif ORACLE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.oracle",
            "NAME": "orclpdb",
            "USER": "cras",
            "PASSWORD": "12345678",
            "HOST": "localhost",
            "PORT": "1521",
            "OPTIONS": {"service_name": "orclpdb"},
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            # "NAME": "bancocras",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
            'OPTIONS': {
            'options': '-c search_path=public,bancocras'
            }
        }
    }

# Cache (default: in-memory for local/dev performance)
CACHES = {
    "default": {
        "BACKEND": os.getenv(
            "CACHE_BACKEND", "django.core.cache.backends.locmem.LocMemCache"
        ),
        "LOCATION": os.getenv("CACHE_LOCATION", "agendamentocras"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        'NAME': 'app.passvalidators.UpperAndLowerCaseValidator'
    },
    {
        'NAME': 'app.passvalidators.SpecialCharacterValidator'
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "PT-BR"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "base_static",
    BASE_DIR / "Frontend" / "dist",
]

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_ROOT = BASE_DIR / "static"


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "perf": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        # Remova 'rest_framework.renderers.BrowsableAPIRenderer'
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        # 'rest_framework.permissions.IsAuthenticated',
        "rest_framework.permissions.DjangoModelPermissions",
    ),
    # "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    # "PAGE_SIZE": 10,
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}


CORS_ALLOWED_ORIGINS = _split_env_list(os.getenv("CORS_ALLOWED_ORIGINS", ""))
if not CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5001",
        "http://localhost:5000",
        "http://localhost:8080",
        "https://dev-agendamentocras.fortaleza.ce.gov.br",
        "https://hom-agendamentocras.fortaleza.ce.gov.br",
        "https://agendamentocras.fortaleza.ce.gov.br",
        "https://acolhe.fortaleza.ce.gov.br"
    ]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False
CORS_EXPOSE_HEADERS = ['Content-Type','X-CSRFToken']

# Ajuste CSRF para permitir o round-trip com o frontend local.
CSRF_TRUSTED_ORIGINS = _split_env_list(os.getenv("CSRF_TRUSTED_ORIGINS", ""))
if not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:5001",
        "http://localhost:8080",
        "https://dev-agendamentocras.fortaleza.ce.gov.br",
        "https://*.dev-agendamentocras.fortaleza.ce.gov.br",
        "https://*.hom-agendamentocras.fortaleza.ce.gov.br",
        "https://*.agendamentocras.fortaleza.ce.gov.br",
        "https://*.hom-acolhe.fortaleza.ce.gov.br"
    ]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtps.fortaleza.ce.gov.br'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
FRONTEND_RESET_PASSWORD_URL = os.getenv("FRONTEND_RESET_PASSWORD_URL")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# CSP CONFIGS
# CSP_REPORT_ONLY = os.getenv("CSP_REPORT_ONLY", "True" if DEBUG else "False").lower() == "true"
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ["'self'", 
                        'https://www.googletagmanager.com', 
                        'https://bootstrap.news/', 
                        'https://encrypted-tbn0.gstatic.com'

                        # 'https://bootstrap.news/', 
                        ],
        "style-src-elem": ["'self'", NONCE,  
                           'fonts.googleapis.com',
                            'fonts.gstatic.com',
                            'https://cdn.jsdelivr.net', 
                            'https://fonts.googleapis.com',
                            'https://cdnjs.cloudflare.com',
                            'https://fonts.googleapis.com/',
                            'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css',
                            'https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css',
                            "'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='",
                            "'sha256-fy6lKwLOTkaWXAYJYXgbsJTw3iUI98EjHWds4POcq7Y='",
                            "'sha256-pHZW5FnKEpgyMCth2rcBCb7YqW3oUPDOh55bu5bY1O0='",
                            "'sha256-9TQbosJW4VoCDawLXBg6p922Odisgeq279TUYjiV3+U='",
                            "'sha256-vrNXQc19Pn+bZLCC/bOSkLx2nfO/mP7uyBJ9aV+7+Bo='",
                            "'sha256-oGOSfGLJBqsFIlXNg7YXJi7w2U0jsXDbYFsfSr28QIc='",
                            "'sha256-JwxBIck75oTDDyL1jpGihuRVsAFs1qE1XRWul6+GXJo='",
                            "'sha256-hMEY6bvaZ1jwHUqU+6TkMhXu7Cj5fP8hXltLH4kSUuQ='",
                            "'sha256-wOopSZvpG/NMeZi4xjwQr/a8MOFulIONRme9R32T1po='",
                            "'sha256-gJ56cMOK4M0WjDG+cKNxPE9V7VpwtJzctJRQdUSmLqQ='",
                            "'sha256-wdyCmVTOTihTtHj8dyAJ40ke9pdr5reBq2bAOU/aVRE='",
                            "'sha256-VBn7l0f0NRvOOf8cSi5Qz9AAIGbI4IDgq+LRXHVW6Ew='",
                            "'sha256-lLtZwwD/Mv7Jv5MBAC6SvrwoZthKCGy5IxTgbFhCihM='",
                            "'sha256-74IXNQJ3DdOd76hQssGzVOSrk6qQMkKJRoQ6LsdmLA4='",
                            "'sha256-PWeyDUWIy2zyT/Z2PtV1OqTgIxI3WYgbLSonAahtRgU='",
                            "'sha256-wxCGm1413xlPrzoLTE9nt2fEn6pJfSPgHIEzwyAuUJc='",
                            "'sha256-CJ1pTsSPTRrN7kQbJW2SiQt9YRKxwB251fbWBesQkPY='",
                            "'sha256-IepggOW3EjqInrrXfF4zIz+VY/0T5O+n0DhBSKuTOwY='",
                            "'sha256-weOHRgCyxBY34NqXGmsSl5MIWOYsfXjS7CblweWmUF0='",
                            "'sha256-V8nvvDZyOkEZn1BaWpwfqVitHwoOGYTCdfPuHDYQTWQ='",
                            "'sha256-TxtHnJCuRTs1NBY8ZMO/TELJ645us7leF9SmHu5Iu7U='",
                            "'sha256-OKhV6W8CcpXNxoqzqb4wRwWbW/cIqp4rz58a+y3gThQ='",
                            "'sha256-CPbcX8uncNyWCSb7jllieXRVs+UcZKTBPL1cmkKJcYQ='",
                            "'sha256-zaSJtcguMv0EGgE6P5HxKIcViDTgmjtXID6fC2feNAY='",
                            "'sha256-vFtu7tdMIXc4LlroPMGLy5iPAGreepPqTFDHNE2CdAg='",
                            "'sha256-FrMyaTxLyv73UJkDIm3BvWzG0g54MQ21Pf7IthsyRg8='"

                            ],
        "script-src": ["'self'", NONCE,
                       'https://www.googletagmanager.com', 
                       'https://cdn.jsdelivr.net/', 
                       'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js', 
                       'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js',
                       'https://vlibras.gov.br/app/vlibras-plugin.js',
                       "'sha256-mLSTMG2T3ztOgpwwEfx6XP8UQURW+9doHjy3CGoGQrM='",
                       "'sha256-NF/fVl45X/0WySgNbHTmxIcpxt+su6aW8VHf5DAM2Pk='",
                       "https://www.vlibras.gov.br/app/vlibras-plugin.chunk.js",
                       "https://vlibras.gov.br/app/target/UnityLoader.js",
                       'https://www.vlibras.gov.br/app/',
                       'https://vlibras.gov.br/app/target/UnityLoader.js',
                       'blob:',
                       "'unsafe-eval'"
                       ],
        "style-src": ["'self'", NONCE, 
                      'fonts.googleapis.com', 
                      'fonts.gstatic.com', 
                      'https://cdnjs.cloudflare.com/', 
                      'https://fonts.googleapis.com/', 
                      'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css', 
                      'https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css',
                      ],
        "font-src": ["'self'", 'fonts.googleapis.com', 
                     'https://cdn.jsdelivr.net/', 
                     'fonts.gstatic.com', 'data:', 
                     'https://fonts.googleapis.com/', 
                     'https://cdn.jsdelivr.net/npm/boxicons@latest/fonts/boxicons.woff2', 
                     'https://cdn.jsdelivr.net/npm/boxicons@latest/fonts/boxicons.ttf', 
                     'https://cdn.jsdelivr.net/npm/boxicons@latest/fonts/boxicons.woff',
                     'https://vlibras.gov.br/app//assets/fonts/'
                     ],
        "connect-src": ["'self'", 
                        'https://www.googletagmanager.com', 
                        'https://www.google-analytics.com/',
                        'https://cdn.jsdelivr.net/',
                        'https://dicionario2.vlibras.gov.br/bundles',
                        'https://vlibras.gov.br/app/target/playerweb.json',
                        'https://vlibras.gov.br/app/target/'
                        ],
        "child-src": ["'self'", 'digital.fortaleza.ce.gov.br', 
                      'dev-digital.fortaleza.ce.gov.br', 
                      'googletagmanager.com', 
                      'web-fdigital-dev-cogect-fdigital-dev.apps.fortaleza.ce.gov.br',
                      
                      ],
        "worker-src": ["'self'", 'blob:'          
        ],
        "object-src": ["'self'", 'digital.fortaleza.ce.gov.br', 
                       'dev-digital.fortaleza.ce.gov.br', 
                       'googletagmanager.com', 
                       'web-fdigital-dev-cogect-fdigital-dev.apps.fortaleza.ce.gov.br'
                       ],
        "form-action": ["'self'", 'digital.fortaleza.ce.gov.br', 
                        'dev-digital.fortaleza.ce.gov.br', 
                        'web-fdigital-dev-cogect-fdigital-dev.apps.fortaleza.ce.gov.br'
                        ],
        "frame-ancestors": ["'self'", 'digital.fortaleza.ce.gov.br', 
                            'dev-digital.fortaleza.ce.gov.br', 
                            'web-fdigital-dev-cogect-fdigital-dev.apps.fortaleza.ce.gov.br'
                            ],
        "img-src": ["'self'", "data:", 
                    'https://i.imgur.com/', 
                    'https://cdn.jsdelivr.net/',
                    'https://b.tile.openstreetmap.org',
                    'https://c.tile.openstreetmap.org',
                    'https://a.tile.openstreetmap.org',
                    'https://unpkg.com/leaflet@1.9.4/dist/images/',
                    'https://vlibras.gov.br/app//assets/',
                    'https://vlibras.gov.br/app//assets/',
                    'https://encrypted-tbn0.gstatic.com'
                    ],
        # "report-only": CSP_REPORT_ONLY, # REMOVER EM PRODUCAO
    }
}

