# Generated by Django 5.2.7 on 2026-01-28 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pergunta', models.CharField(max_length=300, verbose_name='Pergunta')),
                ('resposta', models.CharField(max_length=1000, verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Dúvida Frequente',
                'verbose_name_plural': 'Dúvidas Frequentes',
            },
        ),
    ]
