# Generated by Django 5.2.7 on 2026-10-06 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidadaos', '0010_cidadao_dados_clinicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesafioAutenticacaoCidadao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('telefone', models.CharField(db_index=True, max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_integracao', to='cidadaos.cidadao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessaoCidadao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('telefone', models.CharField(db_index=True, max_length=20)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('authenticated_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_integracao', to='cidadaos.cidadao')),
            ],
            options={
                'indexes': [models.Index(fields=['telefone', 'expires_at'], name='sessao_tel_exp_idx')],
            },
        ),
    ]
