# Generated by Django 5.2.7 on 2026-01-21 12:27
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        UnaccentExtension(),
    ]
