# Generated by Django 5.2.7 on 2026-01-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20260121_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairro',
            options={'ordering': ['nome'], 'verbose_name': 'Bairro', 'verbose_name_plural': 'Bairros'},
        ),
    ]
