# Generated by Django 5.2.7 on 2026-03-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bairro_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='latitude',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='longitude',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Longitude'),
        ),
    ]
