# Generated by Django 5.2.7 on 2026-03-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bairro_latitude_bairro_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bairro',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bairro',
            name='longitude',
        ),
    ]
