# Generated by Django 5.2.7 on 2025-11-17 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
        ('unidade_cras', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaVaga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('vagas', models.PositiveIntegerField(default=1, verbose_name='Profissionais disponíveis')),
                ('vagas_ocupadas', models.PositiveIntegerField(default=0, verbose_name='Vagas ocupadas')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.servico', verbose_name='Serviço')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidade_cras.unidadecras', verbose_name='Unidade Cras')),
            ],
            options={
                'unique_together': {('unidade', 'servico', 'data', 'horario')},
            },
        ),
    ]
