# Generated by Django 5.2.7 on 2025-11-18 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('servicos', '0002_remove_servico_tempo_atendimento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendavaga',
            options={'verbose_name': 'Agenda Vaga', 'verbose_name_plural': 'Agenda Vagas'},
        ),
        migrations.AlterUniqueTogether(
            name='agendavaga',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agendavaga',
            name='tipo_servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='servicos.tiposervico', verbose_name='Tipo de Serviço'),
        ),
        migrations.RemoveField(
            model_name='agendavaga',
            name='servico',
        ),
    ]
