# Generated by Django 5.2.7 on 2025-11-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_agendavaga_options_and_more'),
        ('servicos', '0002_remove_servico_tempo_atendimento_and_more'),
        ('unidade_cras', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendavaga',
            unique_together={('unidade', 'tipo_servico', 'data', 'horario')},
        ),
    ]
