# Generated by Django 5.2.7 on 2025-11-21 12:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_agendavaga_unique_together'),
        ('cidadaos', '0001_initial'),
        ('servicos', '0002_remove_servico_tempo_atendimento_and_more'),
        ('unidade_cras', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(verbose_name='Data do agendamento')),
                ('horario', models.TimeField(verbose_name='Hora do Agendamento')),
                ('situacao', models.CharField(choices=[('AGENDADO', 'Atendimento Agendado'), ('CANCELADO_CIDADAO', 'Cancelado pelo Cidadão'), ('CANCELADO_CRAS', 'Cancelado pelo Cras'), ('AUSENCIA_CIDADAO', 'Ausência do Cidadão'), ('ATIVADO', 'Ativado'), ('ATIVADO_AUSENTE', 'Ativado, mas não compareceu')], default='AGENDADO', max_length=20, verbose_name='Situação do agendamento')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='cidadaos.cidadao', verbose_name='Cidadão')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='servicos.servico', verbose_name='Serviço')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='unidade_cras.unidadecras', verbose_name='Unidade')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='agendamentos.agendavaga', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data', 'horario'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('situacao', 'AGENDADO')), fields=('cidadao', 'servico', 'situacao'), name='um_agendamento_por_servico_por_cidadao')],
            },
        ),
    ]
