# Generated by Django 5.2.7 on 2025-11-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(editable=False, verbose_name='Data do agendamento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.TimeField(editable=False, verbose_name='Hora do Agendamento'),
        ),
    ]
