# Generated by Django 5.2.7 on 2025-11-21 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_alter_agendamento_data_alter_agendamento_horario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='atendente',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups': 'atendente'}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Atendente'),
        ),
    ]
