# Generated by Django 5.2.7 on 2025-11-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_alter_agendamento_atendente'),
        ('servicos', '0002_remove_servico_tempo_atendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_hora_fim_atendimento',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora do final do atendimento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_hora_inicio_atendimento',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora do inicío do atendimento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='observacoes_gerais',
            field=models.TextField(blank=True, null=True, verbose_name='Observações gerais'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servicos_adicionais',
            field=models.ManyToManyField(blank=True, null=True, to='servicos.servico', verbose_name='Serviços adicionais'),
        ),
    ]
