# Generated by Django 5.2.7 on 2025-11-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_agendamento_data_hora_fim_atendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='situacao',
            field=models.CharField(choices=[('AGENDADO', 'Atendimento Agendado'), ('CANCELADO_CIDADAO', 'Cancelado pelo Cidadão'), ('CANCELADO_CRAS', 'Cancelado pelo Cras'), ('AUSENCIA_CIDADAO', 'Ausência do Cidadão'), ('ATIVADO', 'Ativado'), ('ATENDIMENTO', 'Em Atendimento'), ('CHAMANDO', 'Chamando'), ('ATIVADO_AUSENTE', 'Ativado, mas não compareceu')], default='AGENDADO', max_length=20, verbose_name='Situação do agendamento'),
        ),
    ]
