# Generated by Django 5.2.7 on 2025-12-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_alter_agendamento_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='origem',
            field=models.CharField(blank=True, choices=[('156', 'Central 156'), ('RECEPCAO', 'Recepção Cras'), ('SITE', 'Site')], max_length=50, null=True, verbose_name='Origem do agendamento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='situacao',
            field=models.CharField(choices=[('AGENDADO', 'Atendimento Agendado'), ('CANCELADO_CIDADAO', 'Cancelado pelo Cidadão'), ('CANCELADO_CRAS', 'Cancelado pelo Cras'), ('AUSENCIA_CIDADAO', 'Ausência do Cidadão'), ('ATIVADO', 'Ativado'), ('ATENDIMENTO', 'Em Atendimento'), ('CHAMANDO', 'Chamando'), ('ATIVADO_AUSENTE', 'Ativado, mas não compareceu'), ('AGUARDANDO_FILA', 'Aguardando')], default='AGENDADO', max_length=20, verbose_name='Situação do agendamento'),
        ),
    ]
