# Generated by Django 5.2.7 on 2025-12-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0010_agendamento_origem_alter_agendamento_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='origem',
            field=models.CharField(blank=True, choices=[('156', 'Central 156'), ('RECEPCAO', 'Recepção Cras'), ('SITE', 'Site'), ('FILA', 'Fila de Espera')], max_length=50, null=True, verbose_name='Origem do agendamento'),
        ),
    ]
