# Generated by Django 5.2.7 on 2025-12-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0011_alter_agendamento_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='agendamentos.agendavaga', verbose_name='Vaga'),
        ),
    ]
