# Generated by Django 5.2.7 on 2025-12-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0012_alter_agendamento_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_inicio_atendimento',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora do início do atendimento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='situacao',
            field=models.CharField(choices=[('AGENDADO', 'Atendimento Agendado'), ('CANCELADO_CIDADAO', 'Cancelado pelo Cidadão'), ('CANCELADO_CRAS', 'Cancelado pelo Cras'), ('AUSENCIA_CIDADAO', 'Ausência do Cidadão'), ('ATIVADO', 'Ativado'), ('ATENDIMENTO', 'Em Atendimento'), ('CHAMANDO', 'Chamando'), ('ATIVADO_AUSENTE', 'Ativado, mas não compareceu'), ('AGUARDANDO_FILA', 'Aguardando'), ('FINALIZADO', 'Finalizado')], default='AGENDADO', max_length=20, verbose_name='Situação do agendamento'),
        ),
    ]
