# Generated by Django 5.2.7 on 2025-12-17 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0013_alter_agendamento_data_hora_inicio_atendimento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='atendente',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name__in': ['Atendente', 'Supervisor']}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Atendente'),
        ),
    ]
