# Generated by Django 5.2.7 on 2026-01-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0014_alter_agendamento_atendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='motivo_territorio',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de agendamento fora do território'),
        ),
    ]
