# Generated by Django 5.2.7 on 2026-01-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0015_agendamento_motivo_territorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='final_atendimento',
            field=models.CharField(blank=True, choices=[('REALIZADO', 'Realizado'), ('NAO_REALIZADO_REQUISITO', 'Não Realizado - Pré-requisito'), ('NAO_REALIZADO_RECUSA', 'Não Realizado - Recusa do Cidadão'), ('NAO_REALIZADO_RECURSO', 'Não Realizado - Indisponibilidade de Recurso'), ('CANCELADO', 'Cancelado')], null=True, verbose_name='Status final de atendimento'),
        ),
    ]
