# Generated by Django 5.2.7 on 2026-02-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0016_agendamento_final_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='final_atendimento',
            field=models.CharField(blank=True, choices=[('REALIZADO', 'Realizado'), ('NAO_REALIZADO_REQUISITO', 'Não Realizado - Pré-requisito'), ('NAO_REALIZADO_RECUSA', 'Não Realizado - Recusa do Cidadão'), ('NAO_REALIZADO_RECURSO', 'Não Realizado - Indisponibilidade de Recurso'), ('CANCELADO', 'Cancelado')], max_length=200, null=True, verbose_name='Status final de atendimento'),
        ),
    ]
