# Generated by Django 5.2.7 on 2026-02-10 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0017_alter_agendamento_final_atendimento'),
        ('cidadaos', '0007_cidadao_unidade_origem'),
        ('servicos', '0002_remove_servico_tempo_atendimento_and_more'),
        ('unidade_cras', '0006_unidadecras_latitude_unidadecras_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='agendamento',
            name='um_agendamento_por_servico_por_cidadao',
            constraint=models.UniqueConstraint(condition=models.Q(('situacao', 'AGENDADO')), fields=('cidadao', 'servico', 'situacao'), name='um_agendamento_por_servico_por_cidadao', violation_error_message='Já existe um agendamento ativo para este serviço e cidadão.'),
        ),
    ]
