# Generated by Django 5.2.7 on 2026-02-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0018_alter_agendamento_um_agendamento_por_servico_por_cidadao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='motivo_territorio',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Motivo de agendamento fora do território'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='observacoes_gerais',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações gerais'),
        ),
    ]
