# Generated by Django 5.2.7 on 2026-02-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0019_alter_agendamento_motivo_territorio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendavaga',
            options={'ordering': ['data', 'horario'], 'verbose_name': 'Agenda Vaga', 'verbose_name_plural': 'Agenda Vagas'},
        ),
    ]
