# Generated by Django 5.2.7 on 2026-04-01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0020_alter_agendavaga_options"),
        ("unidade_cras", "0008_alter_unidadecras_nome"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChamadaPainel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "cidadao_nome",
                    models.CharField(max_length=200, verbose_name="Cidadão"),
                ),
                (
                    "guiche_nome",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Guichê"
                    ),
                ),
                (
                    "guiche_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="ID do Guichê",
                    ),
                ),
                (
                    "chamado_em",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data/Hora da chamada",
                    ),
                ),
                (
                    "agendamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chamadas_painel",
                        to="agendamentos.agendamento",
                        verbose_name="Agendamento",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chamadas_painel",
                        to="unidade_cras.unidadecras",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chamada do Painel",
                "verbose_name_plural": "Chamadas do Painel",
                "ordering": ["-chamado_em", "-created_at"],
            },
        ),
    ]
