# Generated by Django 5.2.7 on 2026-09-28 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0021_chamadapainel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='atendente',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name__in': ['Médico', 'Enfermeiro', 'Supervisor']}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Atendente'),
        ),
    ]
