# Generated by Django 5.2.7 on 2025-11-14 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade_cras', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaTrabalho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('dias_semana', models.JSONField(default=list, help_text='Selecione um ou mais dias da semana', verbose_name='Dias da Semana')),
                ('turno1_inicio', models.TimeField()),
                ('turno1_fim', models.TimeField()),
                ('turno2_inicio', models.TimeField(blank=True, null=True)),
                ('turno2_fim', models.TimeField(blank=True, null=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas', to='unidade_cras.unidadecras')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
