# Generated by Django 5.2.7 on 2025-11-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_escalatrabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalatrabalho',
            name='turno1_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escalatrabalho',
            name='turno1_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
