# Generated by Django 5.2.7 on 2025-11-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_remove_servico_tempo_atendimento_and_more'),
        ('usuarios', '0003_alter_escalatrabalho_turno1_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='servicos_ofertados',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_ofertados',
            field=models.ManyToManyField(blank=True, to='servicos.tiposervico', verbose_name='Tipo de Serviço'),
        ),
    ]
