# Generated by Django 5.2.7 on 2025-11-26 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade_cras', '0003_guiche'),
        ('usuarios', '0004_remove_usuario_servicos_ofertados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='guiche_atual',
            field=models.ForeignKey(blank=True, help_text='Informe o posto de atendimento em que o atendente está no momento.', null=True, on_delete=django.db.models.deletion.PROTECT, to='unidade_cras.guiche', verbose_name='Guichê/Sala atual'),
        ),
    ]
