# Generated by Django 5.2.7 on 2025-12-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_guiche_atual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cargo_funcao',
        ),
    ]
