# Generated by Django 5.2.7 on 2026-01-08 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidade_cras', '0003_guiche'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaAtendimentoFamiliar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('inscricao', models.CharField(max_length=200, unique=True, verbose_name='Inscrição da Família')),
                ('unidade_de_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidade_cras.unidadecras', verbose_name='Unidade de Atendimento')),
            ],
            options={
                'verbose_name': 'Ficha de Atendimento Famíliar',
                'verbose_name_plural': 'Fichas de Atendimento Famíliar',
            },
        ),
    ]
