# Generated by Django 5.2.7 on 2026-01-08 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('atendimento_familiar', '0001_initial'),
        ('cidadaos', '0006_alter_cidadao_telefone'),
        ('prontuario', '0009_alter_abastecimentoagua_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='abrigo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Endereço é de um Abrigo'),
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.bairro', verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='complemento',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='contato',
            field=models.CharField(blank=True, help_text='Telefone ou e-mail', max_length=250, null=True, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='demanda_apresentada',
            field=models.TextField(blank=True, help_text='Descreva a demanda relatada pela família', null=True, verbose_name='Demanda Apresentada'),
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='forma_ingresso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.formaingresso', verbose_name='Forma de ingresso na unidade'),
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='localizacao',
            field=models.CharField(blank=True, choices=[('URBANO', 'Urbano'), ('RURAL', 'Rural')], max_length=50, null=True, verbose_name='Localização do Domicílio'),
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='observacao',
            field=models.TextField(blank=True, help_text='Use este campo para registrar evoluções, datas e assinaturas', null=True, verbose_name='Observações e evolução dos atendimentos'),
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.orgaoorigemencaminhamento', verbose_name='Orgão'),
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ponto de Referência'),
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='prontuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.prontuario', verbose_name='Nº Prontuário SUAS'),
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cidadaos.cidadao', verbose_name='Identificação do Responsável'),
        ),
        migrations.CreateModel(
            name='MembroFamiliar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('escolaridade', models.CharField(blank=True, choices=[('SEM_ESCOLARIDADE', 'Sem Escolaridade'), ('FUNDAMENTAL_INCOMPLETO', 'Ensino Fundamental Incompleto'), ('FUNDAMENTAL_COMPLETO', 'Ensino Fundamental Completo'), ('MEDIO_INCOMPLETO', 'Ensino Médio Incompleto'), ('MEDIO_COMPLETO', 'Ensino Médio Completo'), ('SUPERIOR_IMCOMPLETO', 'Ensino Superior Incompleto'), ('SUPERIOR_COMPLETO', 'Ensino Superior Completo')], max_length=100, null=True, verbose_name='Escolaridade')),
                ('ocupacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupação')),
                ('renda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidadaos.cidadao', verbose_name='Membro')),
                ('parentesco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.parentesco', verbose_name='Parentesco')),
            ],
            options={
                'verbose_name': 'Membro Famíliar',
                'verbose_name_plural': 'Membros Famíliar',
            },
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='membro_familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atendimento_familiar.membrofamiliar', verbose_name='Membro Famíliar'),
        ),
    ]
