# Generated by Django 5.2.7 on 2026-02-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento_familiar', '0002_fichaatendimentofamiliar_abrigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaatendimentofamiliar',
            name='demanda_apresentada',
            field=models.TextField(blank=True, help_text='Descreva a demanda relatada pela família', max_length=600, null=True, verbose_name='Demanda Apresentada'),
        ),
        migrations.AlterField(
            model_name='fichaatendimentofamiliar',
            name='observacao',
            field=models.TextField(blank=True, help_text='Use este campo para registrar evoluções, datas e assinaturas', max_length=600, null=True, verbose_name='Observações e evolução dos atendimentos'),
        ),
    ]
