# Generated by Django 5.2.7 on 2026-02-26 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento_familiar', '0003_alter_fichaatendimentofamiliar_demanda_apresentada_and_more'),
        ('prontuario', '0059_alter_beneficioseventuais_observacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaatendimentofamiliar',
            name='orgao',
        ),
        migrations.AddField(
            model_name='fichaatendimentofamiliar',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prontuario.unidade', verbose_name='Orgão/Unidade'),
        ),
    ]
