# Generated by Django 5.2.7 on 2026-04-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento_familiar', '0004_remove_fichaatendimentofamiliar_orgao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrofamiliar',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('SEM_ESCOLARIDADE', 'Sem Escolaridade'), ('FUNDAMENTAL_INCOMPLETO', 'Ensino Fundamental Incompleto'), ('FUNDAMENTAL_COMPLETO', 'Ensino Fundamental Completo'), ('MEDIO_INCOMPLETO', 'Ensino Médio Incompleto'), ('MEDIO_COMPLETO', 'Ensino Médio Completo'), ('SUPERIOR_IMCOMPLETO', 'Ensino Superior Incompleto'), ('SUPERIOR_COMPLETO', 'Ensino Superior Completo'), ('CRECHE', 'Creche'), ('EDUCACAO_INFANTIL', 'Educação Infantil'), ('EJA_FUNDAMENTAL_INCOMPLETO', 'EJA - Ensino Fundamental Incompleto'), ('EJA_FUNDAMENTAL_COMPLETO', 'EJA - Ensino Fundamental Completo'), ('EJA_MEDIO_INCOMPLETO', 'EJA - Ensino Médio Incompleto'), ('EJA_MEDIO_COMPLETO', 'EJA - Ensino Médio Completo')], max_length=100, null=True, verbose_name='Escolaridade'),
        ),
    ]
