# Generated by Django 5.2.7 on 2026-02-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Comentário'),
        ),
    ]
