# Generated by Django 5.2.7 on 2025-11-13 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('servicos', '0001_initial'),
        ('unidade_posto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueiohorario',
            name='alterado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloqueios_alterados', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AddField(
            model_name='bloqueiohorario',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloqueios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='servicounidadeposto',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_posto', to='servicos.servico', verbose_name='Serviço'),
        ),
        migrations.AddField(
            model_name='unidadeposto',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.bairro', verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='servicounidadeposto',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_unidade', to='unidade_posto.unidadeposto', verbose_name='Unidade Posto'),
        ),
        migrations.AddField(
            model_name='bloqueiohorario',
            name='unidades',
            field=models.ManyToManyField(related_name='bloqueios', to='unidade_posto.unidadeposto', verbose_name='Unidades Postos'),
        ),
    ]
