# Generated by Django 5.2.7 on 2026-01-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade_posto', '0005_unidadeposto_bairros_abrangencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadeposto',
            name='latitude',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='unidadeposto',
            name='longitude',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Longitude'),
        ),
    ]
