# Generated by Django 5.2.7 on 2026-09-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade_posto', '0008_alter_unidadeposto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicounidadeposto',
            name='mesmo_expediente',
            field=models.BooleanField(default=False, verbose_name='Usar expediente padrão do Posto'),
        ),
    ]
