# Generated by Django 5.2.7 on 2025-11-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='tempo_atendimento',
        ),
        migrations.AddField(
            model_name='tiposervico',
            name='tempo_atendimento',
            field=models.PositiveIntegerField(default=20, verbose_name='Tempo de Atendimento (minutos)'),
        ),
    ]
