# Generated by Django 5.2.7 on 2026-02-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_remove_servico_tempo_atendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classeservico',
            name='descricao',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='descricao',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Descrição'),
        ),
    ]
