# Generated by Django 5.2.7 on 2026-03-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_classeservico_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome do Serviço'),
        ),
    ]
