# Generated by Django 5.2.7 on 2026-09-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_alter_servico_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='envolve_dispensacao',
            field=models.BooleanField(default=False, help_text='Atendimento de entrega de medicamentos, ligado ao estoque da unidade.', verbose_name='Envolve dispensação de medicamentos'),
        ),
        migrations.AddField(
            model_name='servico',
            name='gera_receita',
            field=models.BooleanField(default=False, help_text='Habilita a emissão de receita durante o atendimento deste serviço.', verbose_name='Gera receita'),
        ),
    ]
