# Generated by Django 5.2.7 on 2025-11-28 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidadaos', '0003_alter_cidadao_complemento'),
        ('servicos', '0002_remove_servico_tempo_atendimento_and_more'),
        ('unidade_cras', '0003_guiche'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilaEspera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('prioridade', models.CharField(choices=[('NORMAL', 'Normal'), ('PREFERENCIAL', 'Preferencial'), ('PREFERENCIAL+', 'Preferencial +')], max_length=50, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('AGENDADO', 'Atendimento Agendado'), ('CANCELADO_CIDADAO', 'Cancelado pelo Cidadão'), ('CANCELADO_CRAS', 'Cancelado pelo Cras'), ('AUSENCIA_CIDADAO', 'Ausência do Cidadão'), ('ATIVADO', 'Ativado'), ('ATENDIMENTO', 'Em Atendimento'), ('CHAMANDO', 'Chamando'), ('ATIVADO_AUSENTE', 'Ativado, mas não compareceu')], max_length=50, verbose_name='Status')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidadaos.cidadao', verbose_name='Cidadão')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.servico', verbose_name='Serviço')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidade_cras.unidadecras', verbose_name='Unidade Cras')),
            ],
            options={
                'verbose_name': 'Filas de Espera',
            },
        ),
    ]
