# Generated by Django 5.2.7 on 2025-12-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_espera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filaespera',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Atendimento Agendado'), ('CANCELADO_CIDADAO', 'Cancelado pelo Cidadão'), ('CANCELADO_CRAS', 'Cancelado pelo Cras'), ('AUSENCIA_CIDADAO', 'Ausência do Cidadão'), ('ATIVADO', 'Ativado'), ('ATENDIMENTO', 'Em Atendimento'), ('CHAMANDO', 'Chamando'), ('ATIVADO_AUSENTE', 'Ativado, mas não compareceu'), ('AGUARDANDO_FILA', 'Aguardando')], default='AGUARDANDO_FILA', max_length=50, verbose_name='Status'),
        ),
    ]
