# Generated by Django 5.2.7 on 2025-12-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_espera', '0002_alter_filaespera_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filaespera',
            name='prioridade',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('PREFERENCIAL', 'Preferencial'), ('PREFERENCIAL+', 'Preferencial 80+')], max_length=50, verbose_name='Prioridade'),
        ),
    ]
