# Generated by Django 5.2.7 on 2025-12-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_espera', '0004_alter_filaespera_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='filaespera',
            name='urgencia',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('NORMAL', 'Normal/Sem Urgência')], default='NORMAL', max_length=50, verbose_name='Urgência do atendimento'),
        ),
    ]
