# Generated by Django 5.2.7 on 2025-11-26 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('cidadaos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.bairro', verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='complemento',
            field=models.CharField(blank=True, max_length=150, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
    ]
