# Generated by Django 5.2.7 on 2025-11-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadaos', '0002_cidadao_bairro_cidadao_cep_cidadao_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='complemento',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento'),
        ),
    ]
