# Generated by Django 5.2.7 on 2025-12-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadaos', '0003_alter_cidadao_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='origem',
            field=models.CharField(blank=True, choices=[('156', 'Central 156'), ('RECEPCAO', 'Recepção Cras'), ('SITE', 'Site')], max_length=50, null=True, verbose_name='Origem do agendamento'),
        ),
    ]
