# Generated by Django 5.2.7 on 2025-12-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadaos', '0004_cidadao_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='apelido',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apelido (caso seja relevante)'),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='data_emissao_rg',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão do RG'),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='nis',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='NIS'),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='orgao_emissor',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=10, null=True, verbose_name='Orgão Emissor'),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='rg',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='origem',
            field=models.CharField(blank=True, choices=[('156', 'Central 156'), ('RECEPCAO', 'Recepção Cras'), ('SITE', 'Site'), ('FILA', 'Fila de Espera')], max_length=50, null=True, verbose_name='Origem do agendamento'),
        ),
    ]
