# Generated by Django 5.2.7 on 2025-12-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadaos', '0005_cidadao_apelido_cidadao_data_emissao_rg_cidadao_nis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
