# Generated by Django 5.2.7 on 2026-01-21 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadaos', '0006_alter_cidadao_telefone'),
        ('unidade_posto', '0005_unidadeposto_bairros_abrangencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='unidade_origem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unidade_posto.unidadeposto', verbose_name='Unidade Posto de acompanhamento'),
        ),
    ]
