# Generated by Django 5.2.7 on 2026-02-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadaos', '0007_cidadao_unidade_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='mae',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome da mãe'),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='uf_rg',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF do RG'),
        ),
    ]
