# Generated by Django 5.2.7 on 2026-02-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadaos', '0008_cidadao_mae_cidadao_uf_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='orgao_emissor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Orgão Emissor'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='uf_rg',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True, verbose_name='UF do RG'),
        ),
    ]
