# Generated by Django 5.2.7 on 2026-09-28 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadaos', '0009_alter_cidadao_orgao_emissor_alter_cidadao_uf_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='alergias',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='cns',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{15}$', 'O CNS deve ter 15 dígitos.')], verbose_name='Cartão Nacional de Saúde (CNS)'),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='condicoes_cronicas',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Condições Crônicas'),
        ),
    ]
